- client/js/nonprofits/recurring_donations/index/create.js
This was a missing place where tokenization wasn't implemented.
> Fixes bug where Recurring Donations can't be setup from the backend

- spec/lib/name_copy_naming_algorithm_spec.rb
- spec/lib/slug_copy_naming_algorithm_spec.rb
- spec/lib/slug_nonprofit_naming_algorithm_spec.rb
This shortens test times by a significant amount without reducing coverage that much
> Copy naming algorithms not longer run full max copy tests

- .dockerignore
- Gemfile
- Gemfile.lock
- docker/build/Dockerfile
- docker/debug/Dockerfile
- gems/COPYING
- gems/ruby-qx/README.md
- gems/ruby-qx/lib/qx.rb
- gems/ruby-qx/qx.gemspec
- gems/ruby-qx/test/UpsertTest.rb
- gems/ruby-qx/test/qx_test.rb
- gems/ruby-qx/test/test_insert_user.sql
- gems/ruby-qx/test/test_schema.sql
Houdini is one of the only users of Ruby Qx. Let's just maintain it internally until it can be deprecated at some point.
> Include Ruby Qx into the repo

- app/views/campaigns/_settings_modal.html.erb
- app/views/components/fundraising_pages/_campaigner_profile.html.erb
- app/views/donation_mailer/_donation_changed_amount_table.html.erb
- app/views/donation_mailer/_donation_payment_table.html.erb
- app/views/donation_mailer/_recurring_donation_table.html.erb
- client/js/campaigns/supporters/index/supporter-table.es6
- lib/query/query_donations.rb
- lib/query/query_supporters.rb
- spec/lib/query/query_donations_spec.rb
A set of small p2p improvements
> P2P improvements

- lib/query/query_supporters.rb
- spec/lib/query/query_supporters_spec.rb
End of year export displays and incorrect date for some payments. This fix corrects it.
> Fix bug in end of year export

- app/mailers/export_mailer.rb
- app/views/export_mailer/export_supporter_notes_completed_notification.html.erb
- app/views/export_mailer/export_supporter_notes_failed_notification.html.erb
- lib/export/export_supporter_notes.rb
- lib/job_types/export_supporter_notes_completed_job.rb
- lib/job_types/export_supporter_notes_failed_job.rb
- lib/query/query_payments.rb
- lib/query/query_supporters.rb
- spec/lib/export/export_supporter_notes_spec.rb
- spec/lib/export/export_supporters_spec.rb
- spec/lib/job_types/export_supporter_notes_completed_spec.rb
- spec/lib/job_types/export_supporter_notes_failed_spec.rb
- spec/lib/query/query_supporters_spec.rb
- spec/support/mock_helpers.rb
Some folks as CommitChange to create a Supporter Note export and add additional information to the payment and supporter exports. So they were added.
Enjoy.
> Report improvements

- spec/lib/export/export_supporters_spec.rb
> Fix license

- app/views/donation_mailer/_donation_payment_table.html.erb
- app/views/donation_mailer/nonprofit_payment_notification.html.erb
Not sure I love how we decide to include the campaign creator but it works.
> Fix for campaign creator email being sent to donor

- Gemfile.lock
- NOTICE-ruby
> Update puma and websocket-extensions gems

- NOTICE-js
- package.json
- yarn.lock
> Update websocket-extensions npm package

- Gemfile
- Gemfile.lock
- NOTICE-ruby
[fast_blank](fast_blank) is known to increase the speed of the `ActiveSupport's String#blank?` significantly. We should add it to increase performance.
> Add fast_blank gem

- .storybook/main.js
- NOTICE-js
- app/javascript/stories/index.jsx
- package.json
- yarn.lock
[Storybook](https://storybook.js.org/) is a popular development tool for UI components. Given our heavy UI churn for now, this will be very helpful.
> Add storybook

- NOTICE-js
- babel.config.js
- package.json
- yarn.lock
Add various libraries we'll be using for the front end
> Add Material-UI, Formik and Formik Material-UI

- .github/workflows/full_build.yml
- app/javascript/components/intl/HoudiniIntl.spec.tsx
- app/javascript/components/intl/HoudiniIntl.tsx
- app/javascript/components/intl/index.ts
- app/javascript/components/tests/intl/index.tsx
Currently, we don't build storybooks as part of the CI service. We should because that's important for development! Depends on #333.
> Verify storybook builds

- .storybook/html/main.js
- .storybook/html/preview.js
- .storybook/react/main.js
- .storybook/react/preview.js
- NOTICE-js
- bin/bulid-html-storybook
- bin/start-html-storybook
- package.json
- yarn.lock
We're going to have a small number of plain Javascript and HTML components in Houdini. It'd be nice to have them in storybooks. This change makes that possible.
> Add HTML stories support

- NOTICE-js
- package.json
- yarn.lock
react-error-boundary is the recommended library for React error boundaries. #363 will require them.﻿
> Add react-error-boundary

- app/controllers/nonprofits_controller.rb
- gems/bess/lib/houdini.rb
- gems/bess/lib/houdini/engine.rb
- lib/generators/overrides/rails/plugin/templates/lib/%namespaced_name%/railtie.rb.tt
Depends on #379
- Fix bug in loading countries in nonprofit_controller.rb
- Fix singular-plural mismatch attribute on Houdini::Intl
> Fix a few Houdini::Intl bugs

- .eslintrc.js
- app/javascript/common/yup/yup.spec.ts
- app/javascript/components/formik/MoneyTextField.tsx
The package was added for this but rules were not.
﻿- Add linting for react hooks
- Fix an eslint for hooks issue
- Fix a lint error in a spec file
> Add React Hook ESLint Checking

- .github/workflows/js.yml
- .github/workflows/markdown.yml
- .github/workflows/notice_js.yml
- .github/workflows/notice_ruby.yml
- .github/workflows/ruby.yml
- Update setup-node
- Update setup-ruby
> Update Github actions for the new environment file feature

- .github/ISSUE_TEMPLATE/usability_test.md
- README.md
- docs/contribution_guide_usability_testing.md
Creates a template issue and a contribution guide for usability tests.
> Enable usability testing contributions

- .github/workflows/dependabot-js.yml
- .github/workflows/dependabot-ruby.yml
- Remove unneeded ruby steps from dependabot-js.yml
- Remove unneeded js steps from dependabot-ruby.yml
> Cleanup dependabot notice updating

- app/controllers/ticket_levels_controller.rb
- app/models/event.rb
- app/models/event_discount.rb
- app/models/nonprofit.rb
- app/models/tag_master.rb
- app/models/ticket_level.rb
- db/migrate/20210111220133_set_ticket_level_deleted_to_default_false.rb
- db/structure.sql
- docs/event_definitions/Nonprofit/Event/EventDiscount.ts
- docs/event_definitions/Nonprofit/Event/TicketLevel.ts
- docs/event_definitions/Nonprofit/Event/index.ts
- docs/event_definitions/common.ts
- spec/controllers/ticket_levels_spec.rb
- spec/lib/insert/insert_tickets_spec.rb
- spec/lib/query/query_ticket_levels_spec.rb
- spec/models/ticket_level_spec.rb
Requires #407
Closes #414
Contributes to #415
Contributes to #416
> Event Publisher Support - TicketLevel

- app/controllers/event_discounts_controller.rb
- app/models/event_discount.rb
- app/models/ticket_level.rb
- docs/event_definitions/Nonprofit/Event/EventDiscount.ts
- spec/lib/insert/insert_duplicate_spec.rb
- spec/models/event_discount_spec.rb
- spec/models/ticket_level_spec.rb
> Event Publisher Support - EventDiscount

- app/controllers/campaign_gift_options_controller.rb
- app/models/campaign.rb
- app/models/campaign_gift_option.rb
- db/migrate/20210115230815_set_boolean_defaults_on_campaign_gift_option_to_false.rb
- db/structure.sql
- docs/event_definitions/Nonprofit/Campaign/CampaignGiftOption.ts
- docs/event_definitions/Nonprofit/Campaign/index.ts
- docs/event_definitions/common.ts
- lib/delete/delete_campaign_gift_option.rb
- spec/lib/create/create_campaign_gift_spec.rb
- spec/lib/delete/delete_campaign_gift_option_spec.rb
- spec/models/campaign_gift_option_spec.rb
Depends on #436 
Closes #419 
Affects #410
> Event Publisher Support for CampaignGiftOption

- app/controllers/nonprofits/supporters_controller.rb
- app/models/supporter.rb
- db/migrate/20210119195318_set_anonymous_to_default_to_false.rb
- db/structure.sql
- docs/event_definitions/Nonprofit/Supporter/SupporterAddress.ts
- docs/event_definitions/Nonprofit/Supporter/index.ts
- lib/insert/insert_supporter.rb
- spec/lib/insert/insert_donation_spec.rb
- spec/lib/insert/insert_tickets_spec.rb
- spec/lib/retrieve/retrieve_active_record_items_spec.rb
- spec/lib/update/update_recurring_donations_spec.rb
- spec/models/supporter_note_spec.rb
- spec/models/supporter_spec.rb
> Event Publisher support for SupporterAddress

- docs/event_definitions/Nonprofit/Transaction.ts
We'll flesh out the Transaction object more in the coming days.
Depends on #446
Affects #429
> Create shell of Transaction object

- app/models/supporter_note.rb
- docs/event_definitions/Nonprofit/Supporter/index.ts
- Add 'supporter.*' events to event_definitions
- Correct the tense of a method on SupporterNote
> A few tweaks

- app/controllers/nonprofits/custom_field_masters_controller.rb
- app/models/custom_field_master.rb
- db/migrate/20210204172319_set_default_deleted_to_false_on_custom_field_definition.rb
- db/structure.sql
- docs/event_definitions/Nonprofit/CustomFieldDefinition.ts
- spec/models/custom_field_master_spec.rb
> Add custom_field_definition.* events

- app/models/donation.rb
- app/models/modern_donation.rb
- app/models/transaction.rb
- db/migrate/20210204210627_create_modern_donations.rb
- db/migrate/20210204223643_convert_donation_dedication_to_jsonb.rb
- db/structure.sql
- docs/event_definitions/Nonprofit/Transaction/Donation.ts
- lib/insert/insert_donation.rb
- lib/pay_recurring_donation.rb
- lib/query/query_payments.rb
- lib/update/update_donation.rb
- spec/factories/modern_donations.rb
- spec/lib/insert/insert_donation_spec.rb
- spec/lib/insert/insert_recurring_donation_spec.rb
- spec/lib/query/query_payments_spec.rb
- spec/lib/update/update_donation_spec.rb
- spec/models/modern_donation_spec.rb
- spec/support/contexts/shared_rd_donation_value_context.rb
> Add donation.* events

- app/models/campaign_gift_purchase.rb
- app/models/concerns/model/trx_assignable.rb
- app/models/modern_donation.rb
- app/models/ticket_purchase.rb
> Move common elements of TransactionAssignments to single module

- app/controllers/application_controller.rb
- app/controllers/concerns/controllers/locale.rb
- app/controllers/concerns/controllers/nonprofit/current.rb
- app/controllers/concerns/controllers/supporter/current.rb
- app/controllers/nonprofits/cards_controller.rb
- app/controllers/nonprofits/refunds_controller.rb
- Fix bug in refunds_controller
- Correct the visibility of a few routes
> Fix some incorrectly accessible routes

- app/models/campaign.rb
- app/models/campaign_gift_option.rb
- app/models/campaign_gift_purchase.rb
- app/models/concerns/model/jbuilder.rb
- app/models/custom_field_master.rb
- app/models/event.rb
- app/models/event_discount.rb
- app/models/modern_campaign_gift.rb
- app/models/modern_donation.rb
- app/models/nonprofit.rb
- app/models/supporter.rb
- app/models/supporter_note.rb
- app/models/tag_master.rb
- app/models/ticket_level.rb
- app/models/ticket_purchase.rb
- app/models/ticket_to_legacy_ticket.rb
- app/models/transaction.rb
- spec/models/event_discount_spec.rb
- spec/models/supporter_spec.rb
- spec/support/contexts/shared_donation_charge_context.rb
init_builder puts autofills the id and guesses at the object type﻿
> Make init_builder do more

- app/models/user.rb
- spec/models/user_spec.rb
Given a user, you can call `.super_admin?` to see if they are a super admin
> Add super_admin? method to User

- db/migrate/20210223204824_remove_unused_donation_field.rb
- db/schema.rb
- spec/support/contexts/shared_rd_donation_value_context.rb
There's a category field on Donation but it isn't actually used so it's being removed.﻿
> Remove unused Donation.category field

- Gemfile
- Gemfile.lock
- NOTICE-ruby
- config/application.rb
- config/routes.rb
- db/migrate/20210217225909_create_good_jobs.rb
- spec/requests/good_job_protection_spec.rb
@clarissalimab and I have been having issues with weird behavior from the EventPublisher. Sometimes events are being handled multiple times. We're not quite sure what's going on so we're going to try using good_job on this PR to see if we can address it. If we can, we'll move fully to good_job.
> Change our ActiveJob backend to good_job

- Gemfile
- Gemfile.lock
- NOTICE-ruby
- spec/rails_helper.rb
simplecov was previously removed but we neglected to remove it from the Gemfile.﻿
> Removed unused simplecov gem

- docs/object_event_hook_configs.md
Provides documentation for #453
> Includes documentation for ObjectEventHookConfigs

- app/models/nonprofit.rb
- lib/create/create_campaign_gift.rb
- lib/import/import_civicrm_payments.rb
- lib/insert/insert_bank_account.rb
- lib/insert/insert_custom_field_joins.rb
- lib/insert/insert_duplicate.rb
- lib/insert/insert_payout.rb
- lib/insert/insert_supporter_notes.rb
- lib/update/update_donation.rb
- lib/update/update_payouts.rb
> Removes deprecated 'return's from transaction blocks

- NOTICE-js
- package.json
- yarn.lock
- Add @material-ui/lab so we can use Alert component
- Add @reach/auto-id for generated form ids in React
> A few more packages to prepare for signin

- app/javascript/components/common/progress/AnimatedCheckmark.spec.tsx
- app/javascript/components/common/progress/AnimatedCheckmark.stories.tsx
- app/javascript/components/common/progress/AnimatedCheckmark.tsx
An animated checkmark to illustrate success. Has a role and aria label property for accessibility.﻿
> Add AnimatedCheckmark

- Gemfile
- Gemfile.lock
- NOTICE-ruby
- app/models/nonprofit.rb
- spec/models/nonprofit_spec.rb
- spec/spec_helper.rb
> Updates Nonprofit's website validation

- app/views/campaigns/_campaign_media.html.erb
- config/locales/campaigns.admin.en.yml
> i18n app/views/campaigns/_campaign_media.html.erb

- config/database.yml
- script/compile-assets.sh
- script/db_total_reset.sh
- script/pg_restore_local_from_production.sh
> Replaces 'commitchange' prefix with 'houdini' from databases

- Gemfile
- Gemfile.lock
- NOTICE-js
- NOTICE-ruby
- package.json
- yarn.lock
> Update to webpacker 5.4.0

- app/models/recurrence.rb
- app/models/recurring_donation.rb
- db/migrate/20210602220525_create_recurrences.rb
- db/schema.rb
- docs/event_definitions/Nonprofit/Transaction/Donation.ts
- docs/event_definitions/Nonprofit/Transaction/index.ts
- docs/event_definitions/Recurrence.ts
- docs/event_definitions/common.ts
- lib/insert/insert_recurring_donation.rb
- lib/update/update_recurring_donations.rb
- spec/factories/donations.rb
- spec/factories/recurrences.rb
- spec/factories/recurring_donations.rb
- spec/factories/supporters.rb
- spec/lib/insert/insert_recurring_donation_spec.rb
- spec/lib/update/update_recurring_donations_spec.rb
- spec/models/recurrence_spec.rb
- spec/support/contexts/shared_donation_charge_context.rb
- spec/support/expect.rb
> Event Publishing support for Recurrence

- .rubocop.yml
- app/listeners/object_event_listener.rb
- app/models/offline_transaction_charge.rb
- app/models/offline_transaction_refund.rb
- app/models/payment.rb
- app/models/recurrence.rb
- app/models/stripe_charge.rb
- app/models/subtransaction_payment.rb
- app/models/transaction.rb
- db/migrate/20210412172433_create_offline_transaction_refunds.rb
- db/schema.rb
- spec/factories/offline_transaction_charges.rb
- spec/factories/offline_transaction_refunds.rb
- spec/factories/recurrences.rb
- spec/factories/subtransaction_payments.rb
- spec/factories/subtransactions.rb
- spec/factories/transactions.rb
- spec/models/offline_transaction_refund_spec.rb
- spec/models/recurrence_spec.rb
Depends on #481
Adding a refund mechanism to offline transactions
> Add offline_transaction_refund to object events

- README.md
- config/routes.rb
- docs/friendly_urls.md
> Includes documentation for FriendlyURLs

- app/listeners/object_event_listener.rb
- app/models/stripe_dispute.rb
- app/models/subtransaction_payment.rb
- db/migrate/20210621191202_create_stripe_disputes.rb
- db/schema.rb
- docs/event_definitions/Nonprofit/Transaction/StripeTransaction/Dispute.ts
- docs/event_definitions/Nonprofit/Transaction/StripeTransaction/index.ts
- spec/factories/stripe_disputes.rb
- spec/models/stripe_dispute_spec.rb
> Event publishing for Stripe Disputes

- .rubocop.yml
- app/listeners/object_event_listener.rb
- app/models/charge.rb
- app/models/payment.rb
- app/models/stripe_refund.rb
- app/models/subtransaction_payment.rb
- db/migrate/20210513211918_create_stripe_refunds.rb
- docs/event_definitions/Nonprofit/Transaction/StripeTransaction/Refund.ts
- docs/event_definitions/Nonprofit/Transaction/StripeTransaction/index.ts
- lib/insert/insert_refunds.rb
- spec/factories/stripe_refunds.rb
- spec/lib/insert/insert_refunds_spec.rb
- spec/models/stripe_refund_spec.rb
> Event publishing for Stripe Refund

- Gemfile
- Gemfile.lock
- NOTICE-ruby
- spec/models/transaction_spec.rb
- spec/rails_helper.rb
Shoulda matchers are pretty useful and they make a lot of sense in our specs. I add them here and illustrate t﻿heir use by adding a validation to one spec.
> Add shoulda-matchers and begin using

- app/controllers/api/users_controller.rb
- app/views/api/users/_user.json.jbuilder
- app/views/api/users/current.json.jbuilder
- config/routes.rb
- spec/requests/api/users_controller_spec.rb
- spec/views/api/users/current.json.jbuilder_spec.rb
Creates a REST api for ﻿getting the current logged-in user. Useful for checking whether the current user is logged in.
> Add api/users/current

- app/controllers/api/supporters_controller.rb
- app/views/api/supporters/_supporter.json.jbuilder
- app/views/api/supporters/index.json.jbuilder
- app/views/api/supporters/show.json.jbuilder
- config/routes.rb
- spec/requests/api/supporters_request_spec.rb
- spec/views/api/supporters/index.json.jbuilder_spec.rb
- spec/views/api/supporters/show.json.jbuilder_spec.rb
> Add api/nonprofits/:nonprofit_id/supporters and api/nonprofits/:nonprofit_id/supporters/:id

- app/controllers/api/campaigns_controller.rb
- app/views/api/campaigns/_campaign.json.jbuilder
- app/views/api/campaigns/show.json.jbuilder
- config/routes.rb
- spec/factories/campaigns.rb
- spec/requests/api/campaigns_controller_request_spec.rb
- spec/views/api/campaigns/show.json.jbuilder_spec.rb
> Add api/nonprofits/:nonprofit_id/campaigns/:id

- app/controllers/api/supporter_addresses_controller.rb
- app/views/api/supporter_addresses/_supporter_address.json.jbuilder
- app/views/api/supporter_addresses/index.json.jbuilder
- app/views/api/supporter_addresses/show.json.jbuilder
- config/routes.rb
- spec/requests/api/supporter_addresses_controller_request_spec.rb
- spec/views/api/supporter_addresses/index.json.jbuilder_spec.rb
- spec/views/api/supporter_addresses/show.json.jbuilder_spec.rb
> Add /api/nonprofit/:nonprofit_id/supporters/:supporter_id/supporter_addresses and ../supporter_addresses/:id

- .rubocop.yml
- app/controllers/api/tag_definitions_controller.rb
- app/views/api/tag_definitions/_tag_definition.json.jbuilder
- app/views/api/tag_definitions/index.json.jbuilder
- app/views/api/tag_definitions/show.json.jbuilder
- config/routes.rb
- spec/requests/api/tag_definitions_controller_request_spec.rb
- spec/views/api/tag_definitions/index.json.jbuilder_spec.rb
- spec/views/api/tag_definitions/show.json.jbuilder_spec.rb
> Add /api/nonprofit/:nonprofit_id/tag_definitions and /:id

- .rubocop.yml
- app/controllers/api/custom_field_definitions_controller.rb
- app/views/api/custom_field_definitions/_custom_field_definition.json.jbuilder
- app/views/api/custom_field_definitions/index.json.jbuilder
- app/views/api/custom_field_definitions/show.json.jbuilder
- config/routes.rb
- spec/factories/custom_field_masters.rb
- spec/requests/api/custom_field_definitions_controller_request_spec.rb
- spec/views/api/custom_field_definitions/index.json.jbuilder_spec.rb
- spec/views/api/custom_field_definitions/show.json.jbuilder_spec.rb
> Add /api/nonprofit/:nonprofit_id/custom_field_definitions and /:id

- .rubocop.yml
- app/controllers/api/supporter_notes_controller.rb
- app/views/api/supporter_notes/_supporter_note.json.jbuilder
- app/views/api/supporter_notes/index.json.jbuilder
- app/views/api/supporter_notes/show.json.jbuilder
- config/routes.rb
- spec/factories/supporter_notes.rb
- spec/requests/api/supporter_notes_controller_request_spec.rb
- spec/views/api/supporter_notes/index.json.jbuilder_spec.rb
- spec/views/api/supporter_notes/show.json.jbuilder_spec.rb
> Add /api/nonprofits/:nonprofit_id/supporters/:supporter_id/:supporter_id/supporter_notes and ./:id

- .rubocop.yml
- app/controllers/api/campaign_gift_options_controller.rb
- app/models/campaign_gift_option.rb
- app/views/api/campaign_gift_options/_campaign_gift_option.json.jbuilder
- app/views/api/campaign_gift_options/index.json.jbuilder
- app/views/api/campaign_gift_options/show.json.jbuilder
- app/views/api/common/_amount.json.jbuilder
- config/routes.rb
- docs/event_definitions/Nonprofit/Campaign/CampaignGiftOption.ts
- spec/factories/campaign_gift_options.rb
- spec/models/campaign_gift_option_spec.rb
- spec/models/modern_campaign_gift_spec.rb
- spec/requests/api/campaign_gift_options_controller_request_spec.rb
- spec/views/api/campaign_gift_options/index.json.jbuilder_spec.rb
- spec/views/api/campaign_gift_options/show.json.jbuilder_spec.rb
> Add /api/nonprofits/:nonprofit_id/campaigns/:campaign_id/campaign_gift_options and ./:id

- app/controllers/api/events_controller.rb
- app/views/api/events/_event.json.jbuilder
- app/views/api/events/show.json.jbuilder
- config/routes.rb
- spec/factories/events.rb
- spec/requests/api/events_controller_request_spec.rb
- spec/views/api/events/show.json.jbuilder_spec.rb
> Add /api/nonprofits/:nonprofit_id/events/:id

- .github/workflows/notice_ruby.yml
This is a change that intends to update the notices on dependabot based branches﻿
> Add NOTICE-ruby on dependabot

- .github/workflows/js.yml
- .github/workflows/notice_ruby.yml
- .github/workflows/ruby.yml
> Update workflow to use built-in setup-ruby caching

- .github/workflows/js.yml
- .github/workflows/markdown.yml
- .github/workflows/notice_js.yml
- .github/workflows/ruby.yml
> Use the caching built into setup-node

- Gemfile
- Gemfile.lock
- NOTICE-ruby
Remove pry-byebug as it's causing warnings
Closes #686
Depends on #685
> Remove pry-byebug

- app/controllers/api/transactions_controller.rb
- app/models/nonprofit.rb
- app/models/transaction.rb
- app/views/api/transactions/_transaction.json.jbuilder
- app/views/api/transactions/index.json.jbuilder
- app/views/api/transactions/show.json.jbuilder
- config/routes.rb
- spec/factories/modern_donations.rb
- spec/factories/offline_transaction_charges.rb
- spec/factories/subtransaction_payments.rb
- spec/factories/subtransactions.rb
- spec/factories/transaction_assignments.rb
- spec/factories/transactions.rb
- spec/requests/api/transactions_controller_request_spec.rb
- spec/support/contexts/transaction_context.rb
- spec/views/api/transactions/index.json.jbuilder_spec.rb
- spec/views/api/transactions/show.json.jbuilder_spec.rb
> Add /api/nonprofits/:nonprofit_id/transactions and /:id

- app/controllers/events_controller.rb
- app/javascript/legacy/events/discounts/index.js
- app/javascript/legacy/events/show/page.js
- app/javascript/legacy/ticket_levels/manage.js
- app/javascript/legacy/tickets/index/delete-ticket.js
- app/javascript/legacy/tickets/index/page.js
- app/javascript/legacy/tickets/new.js
- app/javascript/legacy/tickets/wizard.js
- app/views/events/stats.html.erb
- app/views/tickets/index.html.erb
Fixes the problem highlighted in #40 (﻿https://github.com/houdiniproject/houdini/issues/40#issuecomment-923350246).
There's still a bug related to ticket_levels not loading on the event page but this fixes the immediate issue.
> Fix bug preventing creation of events

- app/controllers/api/supporter_notes_controller.rb
- app/views/api/supporter_notes/index.json.jbuilder
- spec/requests/api/supporter_notes_controller_request_spec.rb
- spec/requests/api/supporters_controller_request_spec.rb
- spec/views/api/supporter_notes/index.json.jbuilder_spec.rb
> Add paging to `/api/nonprofits/:nonprofit_id/supporters/:id/supporters_notes`

- app/controllers/events_controller.rb
- app/views/events/show.html.erb
- app/views/events/update.json.jbuilder
- spec/controllers/events_spec.rb
> Fix for inability to update events

- app/views/settings/index.html.erb
Closes #559.
This is partially caused by the integration of bootstrap which is less than ideal. We need to get that pulled out sooner rather than later.﻿
> Settings are now accessible

- app/controllers/campaigns_controller.rb
- app/views/campaigns/_campaign.json.jbuilder
- app/views/campaigns/show.html.erb
- app/views/campaigns/update.json.jbuilder
- spec/controllers/campaigns_spec.rb
> Fix bug on Campaign updating

- Gemfile
- Gemfile.lock
- NOTICE-ruby
I used the incorrect version identifier for date so the version we included wasn't the one we wanted.﻿
> Correct incorrect version of date

- Gemfile
- Gemfile.lock
- NOTICE-ruby
- app/controllers/application_controller.rb
- app/controllers/concerns/controllers/locale.rb
This is based on [this guide](https://guides.rubyonrails.org/i18n.html#choosing-an-implied-locale).
> Use http_accept_language gem to extract locale from request headers

- .storybook/react/preview.js
- NOTICE-js
- package.json
- yarn.lock
There are few fixes in msw-storybook-addon which will help us. So I did the updating :)﻿
> Update msw-storybook-addon to 1.5.0

- app/javascript/components/form_fields/TextField.spec.tsx
- app/javascript/components/form_fields/TextField.stories.tsx
- app/javascript/components/form_fields/TextField.tsx
There's a bit of functionality on TextField which is likely to work but hadn't been formally tested.
Also this correct some docs on TextField
> Adds useful tests to TextField

- app/javascript/hooks/useCurrentUserAuth.ts
By using useAsyncFn, we simplify our hook and standardize.﻿
> Simplify the useCurrentUserAuth hook

- NOTICE-js
- package.json
- yarn.lock
- Run `npx yarn-deduplicate`
- Update react-intl
- Update react-use
- Run yarn-dedupe
- Update NOTICE-js
> Run Yarn dedupe and update some packages

- Gemfile.lock
- NOTICE-ruby
- Bump devise from 4.8.0 to 4.8.1
- Bump jbuilder from 2.11.3 to 2.11.4
- Bump test-unit from 3.5.2 to 3.5.3
> Update gems for 12/20/2021

- app/javascript/components/users/SignInComponent.tsx
Removal of a strange ";" lost on login screen.
Co-authored-by: Paulo Batista <matpaulo@hotmail.com.br>
Because of the need to have a clean login page with no code errors.
* Missing semicolon removed.
> Remove ";" from the login screen

- Gemfile.lock
- NOTICE-js
- NOTICE-ruby
- yarn.lock
- Bump countries from 4.2.1 to 4.2.2
- Bump url-parse from 1.5.3 to 1.5.7
> Update Gems and Yarn packages for 2/21/2022

- .github/ISSUE_TEMPLATE/language_request.md
- README.md
- docs/translations.md
Closes #840.
Depends on https://github.com/houdiniproject/houdini/pull/918.
Depends on #1018
> Document translations process

- Gemfile
- Gemfile.lock
- NOTICE-ruby
Fix for https://github.com/advisories/GHSA-cxf7-qrc5-9446﻿
> Update image_processing to 1.12.2 to fix CVE

- README.md
This aligns with the options `bin/rails houdini:nonprofit:create --help`. I've also included the `[OPTIONAL] ` prefix on relevant arguments.
> Replace --user-phone with --nonprofit-phone in README.md.

- README.md
- docs/getting_started.md
Also fixed link to docs/known_issues.md.
> Update list of dependencies in docs/getting_started.md

- .github/workflows/js.yml
- .github/workflows/markdown.yml
- .github/workflows/notice_js.yml
- .github/workflows/placeholders.yml
- .github/workflows/ruby.yml
In #1088, I had forgotten to update the Node version in the workflows. This addresses that.
> Update Node 14 to latest version for workflows

- app/controllers/cards_controller.rb
- app/controllers/email_settings_controller.rb
- app/controllers/events_controller.rb
- app/controllers/nonprofits/bank_accounts_controller.rb
- app/controllers/recurring_donations_controller.rb
- app/controllers/super_admins_controller.rb
- app/controllers/ticket_levels_controller.rb
- app/controllers/users/sessions_controller.rb
Update some variables to more meaningful names to be more clear of their purpose.
I added a change besides those mentioned in the issue:
[```rds```](https://github.com/houdiniproject/houdini/blob/main/app/controllers/super_admins_controller.rb#L71) -> ```recurring_donations```
Closes #1081
> Replace some variables names

- docs/production_deployment.md
I couldn't see an documentation about how to deploy Houdini in production, so I've added some. I'm a Rails newbie, so I'm sure you'll correct me where I'm heading in the wrong direction. :)
> Add some draft production deployment docs.

- db/migrate/20220427052418_add_active_job_id_concurrency_key_cron_key_to_good_jobs.rb
- db/migrate/20220427052419_add_active_job_id_index_and_concurrency_key_index_to_good_jobs.rb
- db/migrate/20220427052420_add_retried_good_job_id_to_good_jobs.rb
- db/schema.rb
Ran `bin/rails generate good_job:update`. This partially addresses #1105.
> Add missing migrations for GoodJob

- app/controllers/nonprofits_controller.rb
- app/views/nonprofits/show.json.jbuilder
> Fix for NonprofitsController#update causing infinite loop

- docs/payments.md
> Document the process of confirming payments

- Gemfile.lock
- NOTICE-ruby
Fix for CVE-2022-30123 and CVE-2022-30122
> Update to Rack 2.2.3.1

- app/views/layouts/_javascripts.html.erb
- app/views/layouts/_nav_beacon.html.erb
- app/views/nonprofits/btn.html.erb
- app/views/nonprofits/donate.html.erb
- app/views/nonprofits/supporter_form.html.erb
- app/views/super_admins/index.html.erb
The nav beacon isn't really used in Houdini proper so let's just remove it.
> Remove nav_beacon

- NOTICE-js
- yarn.lock
The browserslist DB requested that it be updated. So I am.
> Update browserslist db

- NOTICE-js
- package.json
- yarn.lock
We don't seem to actually use phantomjs-prebuilt so let's remove it!
> Remove unused phantomjs

- NOTICE-js
- package.json
- yarn.lock
- Remove the unused resolve-url-loader
- Remove unused url-loader
> Remove two unneed loaders

- NOTICE-js
- package.json
- yarn.lock
- Remove unused percent package
- Remove unused websocket-extensions package
- Run npx yarn-deduplicate
> Delete two unused NPM packages

- app/javascript/legacy/common/application_view.js
- app/javascript/legacy/common/utilities.js
I noticed that utilities.js has a function called merge. It's no longer needed so I removed it.
> Remove utils.merge

- app/javascript/legacy/common/ajax/check_campaign_or_event_name.js
- app/javascript/legacy/common/ajax/get_campaign_and_event_names_and_ids.js
- app/javascript/routes/nonprofits/campaigns/index.ts
- app/javascript/routes/nonprofits/events/index.ts
- Add routes for name_and_id in Typescript
- Use the common name_and_id routes
> Add routes for nonprofits/:id/{campaigns,events}/name_and_id

- app/javascript/packs/page__bank_accounts__confirm.js
- app/javascript/packs/page__campaigns__index.js
- app/javascript/packs/page__campaigns__peer_to_peer.js
- app/javascript/packs/page__campaigns__show.js
- app/javascript/packs/page__campaigns__supporters__index.js
- app/javascript/packs/page__events__index.js
- app/javascript/packs/page__events__show.js
- app/javascript/packs/page__events__stats.js
- app/javascript/packs/page__nonprofits__button.js
- app/javascript/packs/page__nonprofits__dashboard.js
- app/javascript/packs/page__nonprofits__donate.js
- app/javascript/packs/page__nonprofits__edit.js
- app/javascript/packs/page__nonprofits__payments__index.js
- app/javascript/packs/page__nonprofits__payouts__index.js
- app/javascript/packs/page__nonprofits__recurring_donations__index.js
- app/javascript/packs/page__nonprofits__show.js
- app/javascript/packs/page__nonprofits__supporter_form.js
- app/javascript/packs/page__nonprofits__supporters__index.js
- app/javascript/packs/page__nonprofits__supporters__new.js
- app/javascript/packs/page__profiles__donations_history.js
- app/javascript/packs/page__profiles__fundraisers.js
- app/javascript/packs/page__profiles__show.js
- app/javascript/packs/page__recurring_donations__edit.js
- app/javascript/packs/page__settings__index.js
- app/javascript/packs/page__tickets__index.js
- app/javascript/packs/side-nav.tsx
- app/views/layouts/_side_nav.html.erb
SideNav causes some sort of React error if we don't include it in every bundle.
> Move side-nav into every bundle

- NOTICE-js
- app/javascript/components/common/SideNav/index.tsx
- package.json
- yarn.lock
classnames cleanups adding classnames conditionally to elements. So we're using it.
- Add classnames package
- Use classnames in app/javascript/components/common/SideNav/index.tsx
> Use classnames package

- app/javascript/routes/nonprofits/campaigns/index.ts
- app/javascript/routes/nonprofits/events/index.ts
- app/javascript/routes/nonprofits/payments/index.ts
- app/javascript/routes/nonprofits/supporters/index.ts
- Add individual event route in JS
- Add individual campaign route in JS
- Add payment dashboard detail route
- Add supporter dashboard detail route
> Add Payments and Supporters dashboard details routes as well as individual event and campaign routes

- app/javascript/common/react/index.ts
- app/javascript/components/common/progress/AnimatedCheckmark.tsx
- app/javascript/components/form_fields/MoneyTextField.spec.tsx
- app/javascript/components/form_fields/MoneyTextField.stories.tsx
- app/javascript/components/form_fields/TextField.stories.tsx
- app/javascript/components/users/SignInComponent.tsx
Adds type checking for defaultProps for function components
> Add defaultProps typechecking

- app/views/nonprofits/_achievements.html.erb
- app/views/nonprofits/_edit.html.erb
Based on https://github.com/CommitChange/houdini/pull/419
- Fix bug in app/views/nonprofits/_achievements.html.erb where achievements is nil
- Change a comparison from blank string '' to #blank?
> Fix bug in app/views/nonprofits/_achievements.html.erb where achievements is nil

- app/javascript/legacy/campaigns/new/peer_to_peer_wizard.js
- app/javascript/legacy/campaigns/new/wizard.js
- app/javascript/legacy/campaigns/show/choose-gift-options-modal.js
- app/javascript/legacy/campaigns/show/page.js
- app/javascript/legacy/common/el_swapo.js
- app/javascript/legacy/common/form-to-object.js
- Remove two unused variables in app/javascript/legacy/campaigns/new/peer_to_peer_wizard.js
- Remove unused variables in app/javascript/legacy/campaigns/new/wizard.js
- Remove unused variable in app/javascript/legacy/campaigns/show/choose-gift-options-modal.js
- Remove unused variable in app/javascript/legacy/campaigns/show/page.js
- Remove unused variable from app/javascript/legacy/common/el_swapo.js
- Cleanup app/javascript/legacy/common/form-to-object.js
> Remove some unused variables

- Gemfile
- Gemfile.lock
- NOTICE-ruby
- db/migrate/20220805212521_add_cron_at_to_good_jobs.rb
- db/migrate/20220805212522_add_cron_key_cron_at_index_to_good_jobs.rb
- db/migrate/20220805212523_create_good_job_processes.rb
- db/migrate/20220805212524_index_good_job_jobs_on_finished_at.rb
- db/schema.rb
- spec/requests/good_job_protection_spec.rb
good_job needs to be updated. Not only do we get new shiny things but we can eliminate that infuriating Zeitwerk warning by upgrading.
> Update good_job to 3.3.3

- .eslintrc.js
- NOTICE-js
- app/javascript/components/form_fields/TextField.stories.tsx
- package.json
- yarn.lock
- Add eslint-plugin-storybook
- Add @storybook/testing-library
- Use correct testing library in app/javascript/components/form_fields/TextField.stories.tsx
- Run `npx yarn-deduplicate`
> Add eslint-plugin-storybook

- app/javascript/legacy/campaigns/show/admin.js
- app/javascript/legacy/campaigns/show/page.js
- app/javascript/legacy/events/new/wizard.js
- app/javascript/legacy/events/show/editor.js
- app/javascript/legacy/events/show/page.js
- app/javascript/legacy/gift_options/admin.js
- app/javascript/legacy/gift_options/index.js
- app/javascript/legacy/nonprofits/button/amounts.js
- app/javascript/legacy/nonprofits/button/appearance.js
- app/javascript/legacy/nonprofits/button/designations.js
- app/javascript/legacy/nonprofits/button/footer.js
- app/javascript/legacy/nonprofits/button/hide-dedication.js
- app/javascript/legacy/nonprofits/button/page.js
- app/javascript/legacy/nonprofits/dashboard/page.js
- app/javascript/legacy/nonprofits/show/page.js
- Constify a var in app/javascript/legacy/nonprofits/dashboard/page.js
- Remove an unused import
- Use route in /app/javascript/legacy/nonprofits/dashboard/page.js
- Add routes to app/javascript/legacy/events/show/page.js
- Constify vars in app/javascript/legacy/events/show/page.js
- Constify vars in app/javascript/legacy/nonprofits/show/page.js
- Remove unreferenced const in app/javascript/legacy/events/show/page.js
- Remove unreferenced const in app/javascript/legacy/campaigns/show/page.js
- Constify var in app/javascript/legacy/campaigns/show/page.js
- Remove unneeded debug line in app/javascript/legacy/campaigns/show/page.js
- Cleanup app/javascript/legacy/campaigns/show/admin.js
- Cleanup app/javascript/legacy/events/new/wizard.js
- Cleanup app/javascript/legacy/events/show/editor.js …
> Cleaning up a number of Javascript files

- app/javascript/legacy_react/src/lib/utils.spec.ts
<h1>Description</h1>
Add unit jest tests related to castToNullIfUndef, isBlank, isFilled and castToUndefinedIfBlank functions in app/javascript/legacy_react/src/lib/utils.spec.ts
Closes #1278 
Co-authored-by: Rafaelltm <rafaelltm10@hotmail.com>
Co-authored-by: Carlacangussu <karlacangussu@hotmail.com>
<h1>Motivation for implementing it</h1>
Improve code coverage to houdini project 
<h1>Solution Sumary</h1>
- As suggested by @wwahammy we verified if there were duplicated functions other files. Seeing that was not the case we tested all the functions in app/javascript/legacy_react/src/lib/utils.ts
> Add unit jest tests to all functions in utils

- app/controllers/nonprofits_controller.rb
- app/legacy_lib/nonprofit_metrics.rb
- config/routes.rb
- spec/controllers/nonprofits_spec.rb
This reverts commit 319e8a1299f2202472dd821ee6e5d051a43ffaea.
> Revert "Remove nonprofits/:id/payment_history"

- app/javascript/common/Callbacks/Callback.ts
- app/javascript/common/Callbacks/run.ts
- Improve documentation on Callback.ts
- Improve documentation and simplify the property types in Callbacks/run.ts
> Cleanup the Callback documentation and simplify property types

- package.json
- yarn.lock
Remove explicit @types/prop-types
> Remove @types/prop-types

- README.md
- Replacing rvm with rbenv in readme 
- Resolve Issue : [#1425 -  Installation error on dev setup](https://github.com/houdiniproject/houdini/issues/1425)
Co-Authored-By: [Victor Cabral](https://github.com/victordscabral)
Co-Authored-By: [João](https://github.com/joaobisi)
> Replacing rvm with rbenv in readme

- app/models/nonprofit.rb
Remove an unused method in Nonprofit
> Removed unused `Nonprofit#donation_history_monthly`

- .github/workflows/run-main.yml
These workflows run on main when a new commit is merged to it. It runs the following:
* cache any npm packages so they can be reused by any PRs being pushed to main
* cache any gems so they can be reused by an PRs being pushed to main
* runs linting so eslint and rubocop reports are associated with the main branch
> Add main branch workflows

- README.md
@wwahammy can you see if the changes are correct?
Co-Authored-By: Kayro César <39713656+kayrocesar@users.noreply.github.com>
Co-Authored-By: J <111386960+joaobisi@users.noreply.github.com>
> Separating rbenv install from project setup

- app/models/campaign.rb
- app/models/event.rb
- app/models/profile.rb
- db/migrate/20230421234918_remove_comments.rb
- db/schema.rb
I noticed this in https://github.com/CommitChange/houdini/pull/650 so handling it here too
> Remove the unused Comment class

- app/views/nonprofits/bank_accounts/_modal.html.erb
- app/views/nonprofits/bank_accounts/cancellation.html.erb
- config/locales/en/nonprofits.yml
This PR updates the `bank_accounts` views from `nonprofits` by making them translatable
> Make nonprofits bank_accounts views translatable

- .github/workflows/ruby.yml
- babel.config.js
Helps us catch any bugs like in #1582
> Run `bin/rails assets:precompile` as part of the CI

- docs/getting_started.md
> Document workaround for `relation "active_storage_blobs" does not exist`

- app/assets/stylesheets/global.css.scss
Closes https://github.com/houdiniproject/houdini/issues/1587
This partially reverts commit 5b066f655b5a41b8edf27dfc21a97b198ae97fde.
> Partially revert "Remove references to deleted stylesheets"

- Gemfile
- Gemfile.lock
- NOTICE-ruby
- config/initializers/block_ips.rb
rack-attack is a useful tool but it shouldn't be there by default.
> Remove rack-attack

- Gemfile
- Gemfile.lock
- db/migrate/20230903032645_create_good_jobs_error_event.rb
- db/schema.rb
- Update good_job to 3.18.2
- Update good jobs migration
> Update good job to 3.18.2

- .github/dependabot.yml
- **Fix dependabot issues**
- **No really correct it**
> cleanup dependabot name

- .github/dependabot.yml
- Gemfile.lock
- **Update bundler to 2.2.33**
- **Ignore react-hook-form > 7.52.1**
> ignore react hook form

- babel.config.js
Reverts houdiniproject/houdini#1735
We apparently need these?
> Revert "Get rid of unneeded babel transforms"
