- config/environments/production.rb
Applying the workaround for CVE-2018-3780. Should be best practice anyways.
https://groups.google.com/forum/#!topic/ruby-security-ann/2S9Pwz2i16k
> Add non-compile feature - Fix for CVE-2018-3780

- package.json
- script/build.sh
- script/compile-assets.sh
So there are issues with builds as it relates to non dev instances. The main problem is that when you run a build for environment x, you need access to a development db for environment x. This is inconvenient as the db isn't actually used in any of the builds, it's just required to start rails for the build tasks.
This fix allows us to build for an environment without having that environment's database setup ahead of time. To set the environment x at the command line for a build (or watch), you run the following:
`RAILS_ENV=x npm run build`
The development database has to be available to the build machine. As a work around, you can provide the database via the command line by setting the `BUILD_DATABASE_URL` which sets the `DATABASE_URL` used by the rails build process. By default, it …
> Improvements to builds

- app/controllers/application_controller.rb
- config/environment.rb
- config/initializers/config.rb
- public/maintenance.html
- spec/requests/maintenance_spec.rb
Maintenance is inevitable. Sometimes during maintenance, you need to shut down your Houdini instance and keep the system in a consistent state and guarantee you are the only one who can access it. That's where maintenance mode comes in.
Maintenance mode is feature which directs all non-asset requests to a maintenance page. If someone tries to access your Houdini instance without being logged in, they will receive a 302 redirect to the url in `Settings.maintenance.maintenance_page`. (Note: relative URLs are fine)
Additionally, you can log in yourself by going to `https://example.houdini.domain.to.use/users/sign_in?maintenance_token=MAINTENANCE_TOKEN` where MAINTENANCE_TOKEN is the value of `Settings.maintenance.maintenance_token`
Notably, in maintenance mode, your embedded forms will still …
> Provide support for a maintenance mode

- app/assets/stylesheets/common/minimal.css.scss
- app/views/layouts/apified.html.erb
- app/views/layouts/static.html.erb
- javascripts/app/loading_indicator.ts
The React pages are not working well on IE. This fix makes them work acceptably on IE11, if not ideally. IE10 and, potentially, IE9 should also be supported.
> Fixes for IE11

- Gemfile
- Gemfile.lock
- db/migrate/20180713213748_add_charge_id_indexes.rb
- db/migrate/20180713215825_add_payment_id_to_tickets.rb
- db/migrate/20180713220028_add_indexes_to_refunds.rb
- db/structure.sql
- lib/insert/insert_refunds.rb
- lib/query/query_payments.rb
- spec/lib/insert/insert_donation_spec.rb
- spec/lib/query/query_payments_spec.rb
- spec/support/contexts/shared_donation_charge_context.rb
- spec/support/contexts/shared_rd_donation_value_context.rb
When in the payment view, you can filter by event and campaign. Currently though, we don't include associated refunds with those events. This patch fixes that bug.
> Filtering by event or campaign will include refunds now

- README.md
- dc
- docker/debug/Dockerfile
- run
Previously we'd have issues with docker-compose name conflicts. We now address it by adding a `dc` script (short for docker-compose) which uses a project name based upon the directory of the repo as well as the branch name.
> Improve docker-compose setup

- app/models/supporter.rb
There wasn't an easy way to follow a merged supporter to the supporter it was merged into. Now we have it.
> Add merged_into association for Supporter

- package.json
- swagger.json
Codegen'ed model properties were previously always turned to camelCase. This change makes properties snake_case.
> Turn on proper model property naming

- client/js/components/nonprofit-branding.js
- client/js/recurring_donations/edit/custom-nonprofit-branding.es6
- javascripts/src/lib/nonprofitBranding.ts
There was a bug in the use of the color library. To assist in future work, we move the use of color library into a TS module.
> Move nonprofit branding to a TS file

- app/javascript/legacy/widget/donate-button.v2.js
The widget iframe URL is not correctly percent-encoded. If you include a character in your data-description attribute for your button, you'll create an invalid URL and the server will return a 500 error. This fix properly percent-encodes the URL.
> Fix bug where we don't percent encode parts of the widget iframe URL

- .github/workflows/full_build.yml
- bin/setup
This change makes it so we only need to run yarn install and bundle install a single time and we cache the results. We then reuse the cache in multiple places but don't run yarn and bundle install a bunch of times. That should make the workflow slightly faster.
> Reorganize workflow so we reuse more between steps

- Gemfile
- Gemfile.lock
- app/models/campaign.rb
- config/initializers/houdini_event_publisher.rb
- gems/bess/bess.gemspec
- gems/bess/lib/houdini.rb
- gems/bess/lib/houdini/event_publisher.rb
- gems/bess/lib/houdini/railtie.rb
- lib/insert/insert_donation.rb
- lib/insert/insert_recurring_donation.rb
- lib/insert/insert_refunds.rb
- lib/insert/insert_tickets.rb
- lib/pay_recurring_donation.rb
- spec/lib/insert/insert_donation_spec.rb
- spec/lib/insert/insert_recurring_donation_spec.rb
- spec/lib/insert/insert_tickets_spec.rb
- spec/models/campaign_spec.rb
- spec/support/contexts/shared_rd_donation_value_context.rb
The Houdini event publisher will be a core need going forward and it should be added to Bess. This PR does that.
One missing feature is that Listeners aren't autodetected. This would be a helpful feature going forward.
Depends on #275
> Move event publisher into Bess

- app/javascript/i18n.js.erb
- config/application.rb
There is a [bug](https://github.com/rails/webpacker/issues/2632) in Webpacker which makes long Webpacker compilations, like those in Houdini, fail . This is a temporary workaround for that.
Depends on #290
> Extends webpacker dev proxy timeout

- gems/bess/lib/generators/react/component_generator.rb
- gems/bess/lib/generators/templates/component.js.jsx.tsx
- gems/bess/lib/houdini.rb
- gems/bess/lib/houdini/engine.rb
The react-rails react:component generator has some features that are confusing for our use cases. This change brings the generator and template in-tree and makes the following changes:
* Only Typescript-based components are generated
* Adds the proper license info at the beginning of generated components
* Generates function components, not class components.
> Customize the react-rails generators

- NOTICE-js
- app/javascript/common/money.ts
- included.json
Currently, money is handled as numbers and strings on the front end. This is error prone and makes it difficult to internationalize our UI. To improve the situation, I've added a new Javascript class to Houdini to represent monetary values. It is based on the [js-money](https://github.com/davidkalosi/js-money) package.
Money has the following features:
* Holds the monetary value in the smallest monetary unit, i.e. US dollars are recorded in cents so the values are in an integer.
* Has support for basic arithmetic of multiple money objects, like: `value1.add(value2)`
* Money objects are immutable. In the above example, `value1.add(value2)` creates a new object.
* Has support for comparisons, like: `value1.greaterThan(value2)`
* Prevents operations between two objects with different …
> Add JS Money Type

- .github/workflows/full_build.yml
Reorganizing allows us to speed up our builds since we can do more concurrently
> Reorder the actions on push

- .eslintrc.js
- NOTICE-js
- package.json
- yarn.lock
ESlint, Babel and Webpack all use Javascript but, because they run in node, they require a different set of restrictions. This change does that.
> Setup linting of javascript used by node based build tools

- .github/workflows/full_build.yml
We don't actually build and bundle the Typescript/Javascript on a PR. This addresses that by adding an action for Webpack build and bundling.
> Add a webpack build to the PR actions

- .eslintignore
- NOTICE-js
- app/javascript/common/lodash-joins/hash/hashFullOuterJoin.ts
- app/javascript/common/lodash-joins/hash/hashInnerJoin.ts
- app/javascript/common/lodash-joins/hash/hashLeftAntiJoin.ts
- app/javascript/common/lodash-joins/hash/hashLeftOuterJoin.ts
- app/javascript/common/lodash-joins/hash/hashLeftSemiJoin.ts
- app/javascript/common/lodash-joins/hash/hashRightAntiJoin.ts
- app/javascript/common/lodash-joins/hash/hashRightOuterJoin.ts
- app/javascript/common/lodash-joins/hash/hashRightSemiJoin.ts
- app/javascript/common/lodash-joins/hash/index.spec.ts
- app/javascript/common/lodash-joins/hash/index.ts
- app/javascript/common/lodash-joins/hash/util/index.ts
- app/javascript/common/lodash-joins/hash/util/toStringAccessor.ts
- app/javascript/common/lodash-joins/typings.ts
- app/javascript/common/lodash-joins/util/basicAccessor.ts
- app/javascript/common/lodash-joins/util/basicMerger.ts
- app/javascript/common/lodash-joins/util/index.ts
- app/javascript/common/lodash-joins/util/joinWrapper.ts
- included.json
[lodash-joins](https://github.com/mtraynham/lodash-joins) provides SQL-like joins capabilities for arrays. This is useful is particularly useful for finding the set of changes made to an array. There are some bugs in the packaging lodash-joins so we bring a portion of it into our codebase.
> Add lodash-joins

- app/javascript/components/intl/HoudiniIntl.spec.tsx
- app/javascript/components/intl/HoudiniIntl.tsx
- app/javascript/components/intl/index.ts
- app/javascript/components/tests/intl/index.tsx
The HoudiniIntl components and hooks work just the link the react-intl ones (and use them interally). They reexport all of the react-intl functionality but add a rawFormatMoney function which takes in a Money object formats it according to the current local and options.﻿
> Add HoudiniIntl

- app/javascript/donate-button/donate-button.v2.ts
- app/javascript/legacy/widget/donate-button.v2.js
- app/javascript/legacy_react/src/components/create_offsite_payment_pane/CreateOffsitePaymentPane.tsx
- app/javascript/legacy_react/src/components/edit_payment_pane/EditPaymentPane.tsx
- config/application.rb
Previously we used the offensive terms "blacklist" and "whitelist" instad of "blocklist" and "allowlist". This change corrects this regretable oversight.
As a leader in the Houdini Project, I apologize for this unintentional but unacceptable oversight and anyone harmed by this.
--
One thing to note is that we use NPM package, validator, which uses the term "blacklist" as part of its api for a blocklist.
I believe it would be best to replace that package but I have no done so yet as I haven't had the time. I will create an
issue to track that change being done.
> Correct blocklist/allowlist language

- .storybook/react/preview.js
- app/javascript/components/formik/MoneyTextField.spec.tsx
- app/javascript/components/formik/MoneyTextField.tsx
- app/javascript/components/intl/HoudiniIntl.spec.tsx
- app/javascript/components/intl/HoudiniIntl.tsx
- app/javascript/components/intl/index.ts
- app/javascript/components/tests/intl/index.tsx
- app/javascript/hooks/useIntl.ts
- app/javascript/i18n.js.erb
- package.json
- Rename Intl so you can use normal react-intl interface but only use our module at app/javascript/components/intl
- Extract the Intl decorator for storybook
- Translations regenerate at runtime when using webpack-dev-server or storybook
> Simplify Intl

- app/controllers/nonprofits/tag_masters_controller.rb
- app/models/tag_join.rb
- app/models/tag_master.rb
- db/migrate/20210107210143_set_tag_deleted_to_default_false.rb
- db/structure.sql
- docs/event_definitions/Nonprofit/TagMaster.ts
- docs/event_definitions/Nonprofit/index.ts
- docs/event_definitions/common.ts
- gems/bess/lib/houdini/event_publisher.rb
- spec/models/tag_master_spec.rb
This adds support for events related on TagMaster, specifically tag_master.created and tag_master.deleted
﻿- Set TagMaster.deleted to false
- Add documentation to Houdini::EventPublisher
- EventPublisher Support for TagMaster events
Closes #407
Contributes to #408
> Event Publisher Support - TagMaster

- app/models/concerns/object_event/model_extensions.rb
- app/models/event_discount.rb
- app/models/supporter_note.rb
- app/models/tag_master.rb
- app/models/ticket_level.rb
- spec/models/concerns/object_event/model_extensions_spec.rb
After the first few object_event implementations, it's clear there's an opportunity for reuse here. I've created a concern called `ObjectEvent::ModelExtensions`. By including this concern and calling `object_eventable`, your model receives a `to_event` method which creates a JBuilder representing a particular `object_event`. `to_event` requires a `to_builder` method in the object so it can create the data for the event.
I'm sure we can add things here like lifecycle methods, ways to simplify the to_builder method, etc and I'm not sure these are the best names for the method and module. That said, this seems like a reasonable start.
If there are comments, I'll merge around midday, January 15 CST.
> Move to_event method into a concern

- app/controllers/application_controller.rb
- app/controllers/concerns/controllers/nonprofit/authorization.rb
- app/controllers/concerns/controllers/nonprofit/current.rb
- app/controllers/concerns/controllers/supporter/current.rb
- app/controllers/concerns/controllers/user/authorization.rb
- spec/controllers/concerns/supporter/current_spec.rb
Currently, there's no way to get automatically get the current supporter if running an action with a supporter defined in the path. As an example, if the following call is made:
`GET /nonprofits/1/supporters/2`
inside the `show` action, we'd want `current_supporter` to be the `Supporter` with the id of 2 from the `Nonprofit` with the id of 1.
This fix allows the developer to include a module which provides the `current_supporter` method to get that current supporter.
Important note: `Controllers::Nonprofit::Current` requires the `current_user` for some reason. I don't like this design so we should probably rearrange things.
Depends on #433 
If no comments, will merge around mid-day January 15 CST.
> Concern for getting current_supporter

- docs/event_definitions/common.ts
Some `HoudiniObject`'s will have a string as their primary ID (format TBD), not an integer. This change supports that.﻿
> Allow a string id for HoudiniObjects

- app/models/campaign_gift_option.rb
- app/models/concerns/object_event/model_extensions.rb
- app/models/event_discount.rb
- app/models/supporter.rb
- app/models/supporter_note.rb
- app/models/tag_master.rb
- app/models/ticket_level.rb
- docs/event_definitions/Nonprofit/Transaction.ts
- docs/event_definitions/common.ts
- spec/models/campaign_gift_option_spec.rb
- spec/models/concerns/object_event/model_extensions_spec.rb
- spec/models/event_discount_spec.rb
- spec/models/supporter_note_spec.rb
- spec/models/supporter_spec.rb
- spec/models/tag_master_spec.rb
- spec/models/ticket_level_spec.rb
Some of the Houdini event objects will need a stringy id like a UUID. At the same time, it would be nice to have IDs that communicate what type of object it is, like Stripe does. I've create a form of string ID called HoudIDs which consists of a prefix, an underscore and then 22 random alphanumeric characters. (22 is the number you get when converting a UUID to base 62)
In this PR, they are only used for object events and have the format: "objevt_aBc9..."
> Create HoudIDs for stringy ids

- gems/houdini_upgrade/lib/generators/cw_to_activestorage/templates/initializers/carrierwave.rb.tt
- lib/generators/overrides/rails/plugin/templates/Rakefile.tt
- lib/generators/overrides/rails/plugin/templates/app/controllers/%namespaced_name%/application_controller.rb.tt
- lib/generators/overrides/rails/plugin/templates/app/helpers/%namespaced_name%/application_helper.rb.tt
- lib/generators/overrides/rails/plugin/templates/app/jobs/%namespaced_name%/application_job.rb.tt
- lib/generators/overrides/rails/plugin/templates/app/mailers/%namespaced_name%/application_mailer.rb.tt
- lib/generators/overrides/rails/plugin/templates/app/models/%namespaced_name%/application_record.rb.tt
- lib/generators/overrides/rails/plugin/templates/lib/%namespaced_name%.rb.tt
- lib/generators/overrides/rails/plugin/templates/lib/%namespaced_name%/engine.rb.tt
- lib/generators/overrides/rails/plugin/templates/lib/%namespaced_name%/version.rb.tt
- lib/generators/overrides/rails/plugin/templates/lib/tasks/%namespaced_name%_tasks.rake.tt
- lib/generators/overrides/rails/plugin/templates/rails/application.rb.tt
- lib/generators/overrides/rails/plugin/templates/rails/boot.rb.tt
There was a typo in the license header comments from various trails generators. The last line isn't properly commented so Ruby thinks it's actual code. This fix addresses that.
> Fix typo in generated license comments

- docs/event_definitions/Nonprofit/Transaction.ts
- docs/event_definitions/common.ts
Change the name of our stringy IDs to HouID. This is easier to say and it sounds closer to GUID.
> Change to HouID because it's closer to GUID and easier to say.

- .rspec_parallel
- Gemfile
- Gemfile.lock
- NOTICE-ruby
- config/environments/test.rb
- spec/spec_helper.rb
Parallel tests were a nice idea but ﻿they don't really work well; the output gets so mucked up that it's basically unusable. There's some work being done at https://github.com/rspec/rspec-rails/issues/2104 and https://github.com/ioquatix/turbo_test but nothing is done yet. We should investigate that in the future but until then, let's remove this code and simplify our lives.
> Remove parallel_tests

- Gemfile.lock
- gems/bess/bess.gemspec
- gems/bess/lib/houdini.rb
- gems/bess/lib/houdini/webhook_adapter.rb
- gems/bess/lib/houdini/webhook_adapter/open_fn.rb
As part 1 of #453, adds a webhook that allows triggering jobs or workflows from external tools, with support to OpenFn ([see the documentation](https://docs.openfn.org/)).
1. Navigate to [OpenFn](https://www.openfn.org/signup) and sign up;
2. Set up an authentication method on `Access and Security` option, by clicking on `Add new security protocol`. Choose the API Key auth type;
3. Create a trigger of "Message Trigger" type and define which filter should be in your trigger payload:
4. Navigate to the project view and copy your inbox link.
1. Create an account on [Mailgun](https://signup.mailgun.com/new/signup) (for the sake of testing, a free account is enough);
2. For using the sandbox domain Mailgun provides for testing, add your e-mail as an authorized recipients:
3. On OpenFn, set up …
> Adds a Webhook adapter and includes OpenFn support

- app/models/campaign.rb
- app/models/campaign_gift.rb
- app/models/campaign_gift_option.rb
- app/models/campaign_gift_purchase.rb
- app/models/modern_campaign_gift.rb
- app/models/transaction.rb
- db/migrate/20210208211655_create_campaign_gift_purchases.rb
- db/migrate/20210208212655_create_modern_campaign_gifts.rb
- db/structure.sql
- docs/event_definitions/Nonprofit/Campaign/CampaignGift.ts
- docs/event_definitions/Nonprofit/Campaign/CampaignGiftPurchase.ts
- docs/event_definitions/Nonprofit/Campaign/index.ts
- spec/factories/campaign_gift_purchases.rb
- spec/factories/modern_campaign_gifts.rb
- spec/models/campaign_gift_option_spec.rb
- spec/models/campaign_gift_purchase_spec.rb
- spec/models/modern_campaign_gift_spec.rb
Depends on #469
Closes #475
Closes #420
NOTE: While the object event functionality is here, nothing currently fires these events. This requires the rewrite of the transaction creation mechanism.
Currently, setting the campaign gift is a separate API call after the campaign gift purchase which would be known as not great design. Because of that, it's not really possible to separate out campaign gift purchases and donations.
> Add campaign_gift.* and campaign_gift_purchase.* events

- app/models/nonprofit.rb
- app/models/object_event_hook_config.rb
- db/migrate/20210209002832_create_object_event_hook_configs.rb
- db/structure.sql
- gems/bess/lib/houdini.rb
- gems/bess/lib/houdini/engine.rb
- gems/bess/lib/houdini/webhook_adapter.rb
- gems/bess/lib/houdini/webhook_adapter/open_fn_adapter.rb
- spec/factories/object_event_hook_configs.rb
- spec/models/object_event_hook_config_spec.rb
As part 2 of #453, adds ObjectEventHookConfig to nonprofits, which allows them to create configurations to trigger jobs from external services from events.
You must have registered at least one nonprofit in your database. If you haven't done the OpenFn set up already, proceed with the **OpenFn side** instructions from #472.
To send the trigger request to your inbox, run the following commands:
``` bash
$ rails c
```
``` ruby
> nonprofit = Nonprofit.last
> webhook_service = :open_fn
> object_event_type = 'supporter.update'
> configuration = { headers: { 'x-api-key': <your api key> }, webhook_url: <your inbox url> }
> payload = { 'eventType': 'Update', 'data': 'Some more information about the event' }
> attributes = { webhook_service: webhook_service, configuration: configuration, …
```
> Creates object event hook config

- app/jobs/webhook_transmit_job.rb
- app/listeners/object_event_listener.rb
- app/models/nonprofit.rb
- config/initializers/houdini_event_publisher.rb
- spec/models/nonprofit_spec.rb
Closes #453 
1. Navigate to [OpenFn](https://www.openfn.org/signup) and sign up;
2. Set up an authentication method on `Access and Security` option, by clicking on `Add new security protocol`. Choose the API Key auth type;
3. Create a trigger of "Message Trigger" type and define which filter should be in your trigger payload:
> In this case, we'll be sending an event of type *supporter_note.created*.
4. Navigate to the project view and copy your inbox link.
1. Create an account on [Mailgun](https://signup.mailgun.com/new/signup) (for the sake of testing, a free account is enough);
2. For using the sandbox domain Mailgun provides for testing, add your e-mail as an authorized recipient:
3. On OpenFn, set up your Mailgun credentials on `Credentials`;
4. Create a new job on `Jobs`, by …
> Creates ObjectEventListener and WebhookTransmitJob

- app/controllers/campaigns/supporters_controller.rb
- app/controllers/nonprofits/supporter_notes_controller.rb
- app/controllers/nonprofits/supporters_controller.rb
- lib/insert/insert_supporter_notes.rb
- lib/pay_recurring_donation.rb
- lib/update/update_recurring_donations.rb
- spec/lib/insert/insert_supporter_notes_spec.rb
- spec/lib/update/update_recurring_donations_spec.rb
The supporter creation controller had a bug where it tried to access a nonexisting value for `nonprofit` on its controller. It caused this problem on the supporter creation modal: 
To fix it, I accessed the `current_nonprofit` value instead.
The wrong parameters were being passed to the `InsertSupporterNotes.create` method. It expected a `Supporter`, a `User` and a `content`, from the note to be created. It also had a problem trying to access a symbol that did not exist, as `supporter_params` was a method that returned a string, originally.
> Fixing Supporter and Supporter Note creation

- app/models/object_event_hook_config.rb
- db/migrate/20210218191002_convert_list_of_object_event_types_to_jsonb.rb
- db/schema.rb
- spec/models/object_event_hook_config_spec.rb
jsonb types in Postgres are queriable. If we change ObjectEventHookConfig.object_event_type, it's queriable. That's what we'll do.
﻿- Change list of events to jsonb
- Add validation for length of object_event_types
NOTE: You may have to rebuild your db after this commit.
cc: @clarissalimab
> Change event types for a ObjectEventHookConfig from text to jsonb

- docs/event_definitions/Nonprofit/Campaign/CampaignGift.ts
- docs/event_definitions/Nonprofit/Campaign/CampaignGiftPurchase.ts
- docs/event_definitions/User.ts
- jest.config.js
Jest tries to watch too many things if you have lots of files in the storage directory. This change excludes some directories like `storage` where we know a test will never be.
> Exclude more files from Jest. Also fix a few imports on event definitions

- db/migrate/20210223202458_remove_old_unused_supporter_attributes.rb
- db/schema.rb
Supporter has both a fields and notes attribute. I think these were legacy and they're not used in the code currently so they'll be removed.
> Remove unused attributes from Supporter

- NOTICE-js
- app/javascript/common/money.spec.ts
- app/javascript/common/money.ts
- app/javascript/components/intl/HoudiniIntl.tsx
- package.json
- yarn.lock
`Money` was previously using number for calculations. This was a problem when you multiply by a fractional amount. This change makes `Money` use `BigNumber` internally so calculations are always accurate.
> Have Money use BigNumber

- app/models/campaign_gift_option.rb
- app/models/campaign_gift_purchase.rb
- app/models/modern_campaign_gift.rb
- app/models/modern_donation.rb
- app/models/ticket_level.rb
- app/models/ticket_purchase.rb
- app/models/ticket_to_legacy_ticket.rb
- app/models/transaction.rb
- docs/event_definitions/common.ts
- spec/models/campaign_gift_option_spec.rb
- spec/models/campaign_gift_purchase_spec.rb
- spec/models/event_discount_spec.rb
- spec/models/modern_campaign_gift_spec.rb
- spec/models/modern_donation_spec.rb
- spec/models/ticket_level_spec.rb
- spec/models/ticket_purchase_spec.rb
- spec/models/ticket_to_legacy_ticket_spec.rb
- spec/models/transaction_spec.rb
Previously we weren't using the same fields as Money for monetary values in events. Now we do.﻿
> Migrate to use Money as the base of all monetary values in the event work

- app/javascript/common/money.spec.ts
- app/javascript/common/money.ts
- app/javascript/components/formik/MoneyTextField.spec.tsx
- app/javascript/components/formik/MoneyTextField.stories.tsx
- app/javascript/components/formik/MoneyTextField.tsx
- app/models/campaign_gift_option.rb
- app/models/campaign_gift_purchase.rb
- app/models/modern_campaign_gift.rb
- app/models/modern_donation.rb
- app/models/ticket_level.rb
- app/models/ticket_purchase.rb
- app/models/ticket_to_legacy_ticket.rb
- app/models/transaction.rb
- docs/event_definitions/common.ts
- spec/models/campaign_gift_option_spec.rb
- spec/models/campaign_gift_purchase_spec.rb
- spec/models/event_discount_spec.rb
- spec/models/modern_campaign_gift_spec.rb
- spec/models/modern_donation_spec.rb
- spec/models/ticket_level_spec.rb
- spec/models/ticket_purchase_spec.rb
- spec/models/ticket_to_legacy_ticket_spec.rb
- spec/models/transaction_spec.rb
We're going to use [Money](https://github.com/RubyMoney/money) internal to Ruby going forward.﻿ Since that's the case, our external Javascript Money class should also use the same field names. This fix does that.
> Changed money to use "cents" so it's consistent with ruby-money Money object

- .github/workflows/js.yml
- .github/workflows/markdown.yml
- .github/workflows/notice_js.yml
- .github/workflows/notice_ruby.yml
- .github/workflows/placeholders.yml
- .github/workflows/ruby.yml
When ubuntu-latest changed from 18.04 to 20.04, our caches became invalid. This will happen in two years again. We'll just be more specific and set it to 20.04 to avoid this problem in the future.﻿
> Change ubuntu-latest to specific version (ubuntu-20.04)

- Gemfile
- Gemfile.lock
- NOTICE-ruby
heroku-deflater is only really used on servers where you have no other way to serve compressed assets, like heroku. Since that's sort of a special c﻿ase, the change commments out the heroku-deflater gem line.
> Remove heroku-deflater from production

- docs/event_definitions/Nonprofit/Transaction/StripeTransaction/index.ts
Multiple PRs are going to be adding things to StripeTransaction so it makes sense to have the file added ahead of time since they'll all be referring to it.
> Add the shell of a StripeTransaction interface

- README.md
We now use GoodJob which works great for both development and production mode.
> Remove reference to using a different ActiveJob provider

- .github/workflows/dependent-issues.yml
Now when an PR has "Depends on ﻿#PRNUM", this tool blocks merging until that other PR is resolved.
> Add dependent issues

- app/controllers/concerns/controllers/x_frame.rb
- app/controllers/nonprofits_controller.rb
- spec/controllers/nonprofits_spec.rb
In order to embed a donate widget, the X-Frame-Options header cannot be set on /nonprofits/:id/btn or /nonprofits/:id/donate. By default, Rails sets this. This change removed the X-Frame-Options headers for these two actions.
> Allow framing of nonprofits/:id/donate and nonprofits/:id/btn

- app/models/nonprofit.rb
- spec/models/nonprofit_spec.rb
Validates that the time zones used by the nonprofits are the ones that come from `ActiveSupport::TimeZone`, which are also compatible with Postgresql.
> Validates nonprofit's timezone

- Gemfile.lock
- NOTICE-ruby
We updated to Ruby 2.7.3 but parser wasn't updated to support it yet. This change corrects that.﻿
> Update parser so it stops warning when using Ruby 2.7.3

- spec/support/contexts.rb
Previously we had to manually require all the files in spec/support/contexts. Now they're automagically loaded. What a world!﻿
> Automagically load all the context files for spec testing

- Gemfile
- Gemfile.lock
According to https://github.com/basecamp/mail_view, the mail_view﻿ gem is included in Rails starting in Rails 4.1. We remove it from being explicitly included in the Gemfile.
> mail_view is now included in Rails so not needed in Gemfile

- config/routes.rb
It's easier to catch changes in routes if they're alphabetized. So we're doing that!﻿
> Alphabetize api/nonprofits/* routes

- tsconfig.json
We were accidentally having typescript load all of the files in every subfolder known to humanity. This limits the folders significantly.﻿
> Reduce the number of unnecessary files that typescript is loading

- .github/workflows/notice_ruby.yml
The NOTICE-ruby verification workflow had a bug. This fixes said bug.
> Fix NOTICE-ruby verification bug

- .github/dependabot.yml
- .github/workflows/dependent-issues.yml
- .github/workflows/greetings.yml
- .github/workflows/js.yml
- .github/workflows/markdown.yml
- .github/workflows/notice_js.yml
- .github/workflows/notice_ruby.yml
- .github/workflows/ruby.yml
We currently run builds when anything happens to a pull request, including when they're closed. It's a waste of limited build resources. 
With this change, builds only run when a pull request is opened, reopened, or updated (synchronized).
Also, I've added some forgotten license headers on the YML files in the .github directory
> Reduce number of pull_request events where the build runs

- .github/dependabot.yml
I'm doing dependabot update testing elsewhere so this isn't needed for now.﻿
> Remove dependabot notifications for the test-dependabot branch

- .github/dependabot.yml
Semver major changes are likely to cause chaos so we're ignoring them for now on bundler﻿
> Ignore semver major changes for dependabot updates

- .github/workflows/js.yml
- .github/workflows/markdown.yml
- .github/workflows/ruby.yml
Currently, we run tests on pushes. Since we use PRs for any of the prod branches, this is redundant and fills up the build resources for no reasons.
> Remove tests on push

- spec/spec_helper.rb
We get a warning on the latest version of DatabaseCleaner so this addresses that﻿
> Removed a deprecated arg for DatabaseCleaner

- .rubocop.yml
Rubocop TargetRubyVersion was accidentally 2.6﻿ even though we're on 2.7. This change corrects this.
> Update TargetRubyVersion in rubocop to 2.7

- .github/workflows/placeholders.yml
- .github/workflows/ruby.yml
I moved rubocop out into a separate workflow job and integrated with the code scanning functionality of Github. Not sure this is the best design but I'm submitting it here for review for us to decide.
What do you think @clarissalimab ?
> Move rubocop into its own workflow 

- .github/workflows/js.yml
- .github/workflows/ruby.yml
Previously, if a bundler or yarn cache didn't exist, each job would concurrently try to download the packages. Additionally, some of these workflows would fail so the cached packages would have be regenerated on the next build. This moves package downloading into its own job. As long as the packages download, they'll be cached. Big workflow tasks will depend on the package download job.
> Add a cacheable package download to big workflows

- .eslintrc.js
Currently, we're use all eslint-plugin-jest rules and some of them aren't that useful. I tried to move the few that are useful into the config.
> Only use eslint-jest/style and ./recommended rules

- app/controllers/api/transactions_controller.rb
- app/controllers/concerns/controllers/api/transaction/current.rb
- config/routes.rb
- spec/controllers/concerns/api/transaction/current_spec.rb
Currently, we use the id param in the API for the last item in a route. For example, if you wanted a transaction via the API, it would be `﻿/api/nonprofits/:nonprofit_id/transactions/:id`. This is normally fine but it gets awkward when you have a nested resource. Then it becomes: `/api/nonprofits/:nonprofit_id/transactions/:transaction_id/subtransactions/:id`. This makes it difficult have a single method like `current_transaction` to get the current transaction because the param being checked varies.
This PR changes changes the routes so use  `/api/nonprofits/:nonprofit/transactions/:transaction_id`. This also allows us to create a concern to get current transaction via `current_transaction`.
> Rename the id param in APIs to transaction_id and create a `current_transaction` concern

- .eslintignore
- types/rails__activestorage/index.d.ts
- types/storybook-addon-intl/index.d.ts
- types/storybook-addon-intl/shared.d.ts
There were some missing licenses on some TS types definitions. I've marked them as having the license of the packages they describe and I don't see how that's a problem; we could go with LGPL﻿ but that seems wrong since it seems like the types for a package should match that package.
> Remove activestorage from eslint and add missing licenses on TS type defs

- NOTICE-js
- package.json
- yarn.lock
- Bump merge-deep from 3.0.2 to 3.0.3
- Bump dns-packet from 1.3.1 to 1.3.4
- Bump ws from 6.2.1 to 6.2.2
- Bump lodash from 4.17.19 to 4.17.21
- Bump hosted-git-info from 2.8.8 to 2.8.9
> Update node dependencies with security vulnerabilities

- .github/workflows/dependent-issues.yml
This reverts commit 67b21c915197e81062ce917637adfe7f595686f2.
The original change seemed to break dependent-issues workflow. This reverts that.
depends on: #864
> Revert "Removes some workflow permissions to better security"

- app/controllers/concerns/controllers/api/transaction/current.rb
- config/routes.rb
Rails routing does weird stuff when you rename the id for resources so this reverts the change﻿
> Revert change to using transaction_id as param for transactions in routes

- .github/workflows/ruby.yml
- Gemfile
- Gemfile.lock
- NOTICE-ruby
- spec/lib/format/name_spec.rb
- spec/spec_helper.rb
- turbo_test.rb
[turbo_test](https://github.com/ioquatix/turbo_test) is a parallelized spec runner. It shrinks build time from 8-10 minutes to 3 on my computer.
This is a draft PR to look at how well this actually works in practice.
Follow-up: after testing, we found it works well on my computer but doesn't help on the build. Therefore, we don't use it on the build but make it available to developers on their own machines.
> Add support for turbo_test

- .github/workflows/js.yml
- .github/workflows/ruby.yml
The PostgreSQL version in the README.md is ﻿12 but we were using 11 in the build. This corrects that oversight.
> Use PG v12 in the build script

- app/javascript/hooks/useSteps.spec.ts
- app/javascript/hooks/useSteps.ts
This was an oversight in the useSteps hook﻿.
> useSteps hook now supports steps that have more than one property

- app/views/layouts/_footer.html.erb
We had a warning to tell people that they need to upgrade their to at least IE9. We don't support anything lower than IE11 and only barely that. Let's remove this.﻿
> Remove old IE warning

- NOTICE-js
- yarn.lock
During some work on moving to react-hook-form, I realized how many duplicated packages we had. After a bit of investigation, I settled on using yarn-deduplicate. We have fewer duplicated packages which means our compilations should be smaller.
﻿- Ran `npx yarn-deduplicate --packages ajv`
- Ran `npx yarn-deduplicate --packages tslib`
- Ran `npx yarn-deduplicate --packages whatwg-url`
- Ran `npx yarn-deduplicate --packages qs`
- Ran `npx yarn-deduplicate --packages moment decimal.js`
- Ran `npx yarn-deduplicate --packages lodash-es`
- Cleanup of straggling yarn packages
- Update NOTICE-js
> Deduplicate yarn packages

- app/javascript/hooks/useCurrentUser.ts
- app/javascript/hooks/useCurrentUserAuth.ts
Closes #904 (I think)
- useCurrentUser.revalidate uses the proper mutate arguments
- Migrate useCurrentUserAuth to useReducer and correct a promise bug
> Correct some things in useCurrentUser/Auth

- package.json
- yarn.lock
- Remove unused react-is from package.json
- Run `npx yarn-deduplicate --packages react-is`
> Remove react-is from package.json as it is unused

- Gemfile
- Gemfile.lock
- NOTICE-ruby
- Bump rubocop-rails from 2.13.1 to 2.13.2
- Bump listen from 3.7.0 to 3.7.1
- Bump bootsnap from 1.9.3 to 1.10.1
- Bump countries from 4.1.3 to 4.2.1
> Update gems for Jan 18, 2022

- Gemfile
- Gemfile.lock
- NOTICE-js
- NOTICE-ruby
- yarn.lock
- Bump react_on_rails from 12.5.2 to 12.6.0
- Bump node-fetch from 2.6.1 to 2.6.7
> More updates for January 24, 2022

- app/controllers/api/payments_controller.rb
- app/controllers/api/subtransaction/payments_controller.rb
- app/legacy_lib/insert_donation.rb
- app/legacy_lib/insert_recurring_donation.rb
- app/legacy_lib/insert_refunds.rb
- app/legacy_lib/insert_tickets.rb
- app/legacy_lib/pay_recurring_donation.rb
- app/models/concerns/model/subtransactable.rb
- app/models/offline_transaction.rb
- app/models/stripe_transaction.rb
- app/models/subtransaction.rb
- app/models/transaction.rb
- app/views/api/payments/index.json.jbuilder
- app/views/api/subtransactions/_subtransaction.json.jbuilder
- app/views/api/transactions/_transaction.json.jbuilder
- spec/factories/subtransactions.rb
- spec/legacy_lib/insert/insert_donation_spec.rb
- spec/legacy_lib/insert/insert_recurring_donation_spec.rb
- spec/legacy_lib/insert/insert_refunds_spec.rb
- spec/models/campaign_gift_purchase_spec.rb
- spec/models/modern_campaign_gift_spec.rb
- spec/models/offline_transaction_dispute_spec.rb
- spec/models/offline_transaction_refund_spec.rb
- spec/models/stripe_dispute_spec.rb
- spec/models/stripe_refund_spec.rb
- spec/models/transaction_spec.rb
- spec/requests/api/payments_controller_request_spec.rb
- spec/support/contexts/payment_context.rb
- spec/support/contexts/subtransaction_context.rb
- spec/views/api/payments/show.json.jbuilder_spec.rb
It solves an ambiguity in the name of `subtransaction_payments` entity.
Closes: #967 
Co-authored-by: @alan-ms <alan.sousa@protonmail.com>
This name is redundant and only really exists because we have a legacy entity already called Payment.
In the solution was implemented an alias that makes possible to refer to `subtransaction_payments` entity as `payments`.
> Rename subtransaction_payments to payment

- app/javascript/components/users/SignInComponent.tsx
Thanks to the authors of #1012, a small bug in the use of isMounted was found. This may correct some errors in jest tests but who knows?
﻿Co-authored-by: JoaoVitorFarias <jvlopesfarias@gmail.com>
Co-authored-by: GuilhermeBraz <gvcerveirabraz@gmail.com>
> Correct bug where isMounted wasn't actually being called as a function.

- .github/workflows/ruby.yml
- Gemfile
- Gemfile.lock
- NOTICE-ruby
- app/controllers/image_attachments_controller.rb
- app/legacy_lib/import_civicrm_payments.rb
- app/models/concerns/model/jbuilder.rb
- app/models/concerns/model/subtransactable.rb
- app/views/api/payments/show.json.jbuilder
- spec/requests/users/sessions_controller_request_spec.rb
- spec/views/api/payments/show.json.jbuilder_spec.rb
Two bugs caused us to think tests were passing when they weren't. The problem was that we were using turbo_test which doesn't always return a non-zero error code. The intent
of using turbo_test is that we could go faster on a multicore machine but the github runners aren't multicore so it's pointless.
Additionally, the use of fastener in #975 broke some code that we didn't catch. This reverts most of the changes from that PR.
- Correct some bugs which weren't caught due to using turbo_test
- Use the correct 'rake spec' instead of turbo_test
> Correct specs broken by fastener and not caught by turbo_test

- Gemfile
- Gemfile.lock
From discussion in #524. May potentially break fonts, but is more important that the application can start up in production mode.
> Remove font_assets dependency

- docs/getting_started.md
When I run `yarn watch` I get:
```
$ yarn watch
yarn run v1.22.17
$ /home/ben/houdini/node_modules/.bin/watch
Usage: watch <command> [...directory] [--wait=<seconds>] [--filter=<file>] [--interval=<seconds>] [--ignoreDotFiles] [--ignoreUnreadable] [--ignoreDirectoryPattern]
Done in 0.17s.
```
Should it be `yarn webpack --watch` instead?
> Update docs on building JS in development

- app/views/campaigns/peer_to_peer.html.erb
- app/views/campaigns/show.html.erb
- app/views/campaigns/supporters/index.html.erb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
- app/views/events/stats.html.erb
- app/views/layouts/_javascripts.html.erb
- app/views/nonprofits/bank_accounts/confirmation.html.erb
- app/views/nonprofits/btn.html.erb
- app/views/nonprofits/button/advanced.html.erb
- app/views/nonprofits/button/basic.html.erb
- app/views/nonprofits/button/guided.html.erb
- app/views/nonprofits/dashboard.html.erb
- app/views/nonprofits/donate.html.erb
- app/views/nonprofits/payments/index.html.erb
- app/views/nonprofits/payouts/index.html.erb
- app/views/nonprofits/recurring_donations/index.html.erb
- app/views/nonprofits/show.html.erb
- app/views/nonprofits/supporter_form.html.erb
- app/views/nonprofits/supporters/index.html.erb
- app/views/nonprofits/supporters/new.html.erb
- app/views/profiles/donations_history.html.erb
- app/views/profiles/fundraisers.html.erb
- app/views/profiles/show.html.erb
- app/views/recurring_donations/edit.html.erb
- app/views/settings/index.html.erb
- app/views/super_admins/index.html.erb
- app/views/tickets/index.html.erb
We were incorrectly using javascript_pack_tag in places where javascript files were being split into chunks by webpacker. In that case, we should use javascript_pack_with_chunk_tags. This change does so.﻿
Closes #1060
> Switch to using javascript_packs_with_chunks_tag

- README.md
- app/legacy_lib/nonprofit_creation.rb
- commands/rails/commands/houdini/nonprofit/create/create_command.rb
- spec/legacy_lib/nonprofit_creation_spec.rb
Closes #1079
@BenStrumfels and @WeillerFernandes noticed that the documentation for houdini:nonprofit:create doesn't match the behavior.
The change does the following:
* Correctly sets super_admin status of the admin when `--super-admin` is used
* Changes the meaning of `--confirm-user` to autoconfirm the user on creation and sets it to true by default
* Correct the autoconfirmation of the user on creation
> Correct bugs in houdini:nonprofit:create and flip the meaning of confirm_admin

- Gemfile
- Gemfile.lock
- NOTICE-ruby
- Bump pg from 1.3.4 to 1.3.5
- Bump lograge from 0.11.2 to 0.12.0
- Bump debug from 1.4.0 to 1.5.0
> Update Gems for April 4, 2022

- NOTICE-js
- package.json
- yarn.lock
Moment has a CVE which can only be exploited when running on a server with access to a filesystem. Since we don't use moment like that, this bug would never be exploited. But it doesn't hurt to upgrade anyway.
Bumps [moment](https://github.com/moment/moment) from 2.29.1 to 2.29.2.
- [Release notes](https://github.com/moment/moment/releases)
- [Changelog](https://github.com/moment/moment/blob/develop/CHANGELOG.md)
- [Commits](https://github.com/moment/moment/compare/2.29.1...2.29.2)
---
updated-dependencies:
- dependency-name: moment
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
> Bump moment from 2.29.1 to 2.29.2

- app/assets/stylesheets/components/modals.css.scss
- app/views/common/_modal_close.html.erb
- app/views/settings/_users.html.erb
Issue https://github.com/houdiniproject/houdini/issues/8
Some elements from configurations page "organization users" are not fully accessible. For example, clickable elements not being focusable and lack of aria-label for images.
This PR focus on solving these issues.
> Configurations page "organization users" improve accessibility

- app/controllers/nonprofits_controller.rb
- config/routes.rb
- spec/controllers/nonprofits_spec.rb
We only allow Nonprofits to be created via CLI so we shouldn't be allowing people to register a nonprofit via an API.
> Remove unused NonprofitsController#create

- app/controllers/cards_controller.rb
The `acct` variable wasn't resolved properly when conflicts in this method were merged. One called it `acct` the other renamed to `account`.
> Fix conflict with `acct` variable renaming

- app/controllers/nonprofits/refunds_controller.rb
This change modifies `charge_params` to fix the `ArgumentError` mentioned in #1103 and to return a hash of the shape expected by `create`. I've used a symbol for `:refund` for consistency with `:charge_id` being a symbol. Would it be better to split these out into two functions though? Seems unclear to call the same function twice.
I've also removed the line setting `:user_id` because I can't see how it it does anything, though I may be unaware of some magic here.
I'm not very familiar with Ruby/Rails, but I'm keen to learn. :)
> Fix charge_params used during refund

- Gemfile
- Gemfile.lock
- NOTICE-js
- NOTICE-ruby
We don't even use prerendering for react components but if we did, the Node execjs renderer would likely be the best option.
This change removes mini_racer; mini_racer has been hard to update due to bugs in Bundler. This solves that problem too! Should also speed up the builds a bit.
> Use Node Runtime for Execjs

- app/javascript/api/users.ts
Devise has an bad behavior where if you have http_authenticatable set to true, then it responds with the WWW-Authenticate header. This triggers the browser to popup the native Username and Password login modal. We correct this by adding the X-Requested-With header to our POST to user sign request.
> Mention that we're XHR in postSignIn so Devise doesn't start the browser based login

- app/legacy_lib/insert_donation.rb
- app/legacy_lib/insert_recurring_donation.rb
Based on https://github.com/CommitChange/houdini/pull/382
If you look at `.locale_for_supporter` in `InsertDonation` and `InsertRecurringDonation`, it's not really useful. You can do the same far more simply by taking a `Supporter` object and calling `#locale` . So we're doing that now.
> Remove the locale_for_supporter methods in InsertRecurringDonation and InsertDonation

- app/controllers/campaigns_controller.rb
- app/models/campaign.rb
- app/views/campaigns/show.html.erb
- db/migrate/20220608214048_remove_recurring_fund_from_campaigns.rb
- db/schema.rb
- spec/legacy_lib/insert/insert_duplicate_spec.rb
There's a column called `recurring_fund` on `Campaign`. I can't find any place that it's used so let's remove it.
> Remove unused `Campaign#recurring_fund`

- app/javascript/api/users.ts
- config/initializers/devise.rb
This prevents Devise from ever running a WWW-Authenticate header when unauthorized. The WWW-Authenticate causes a browser login window to popup which is awful.
This correctly fixes the issue in #1130
> Override FailureApp so we never have a auth popup in the browser

- Gemfile
- Gemfile.lock
- NOTICE-ruby
- Bump pg from 1.3.5 to 1.4.0
- Bump rubocop-rails from 2.14.2 to 2.15.0
> Update Gems for June 20, 2022

- .github/dependabot.yml
I think it makes sense to allow semver updates for Github actions in dependabot. We do need to be careful but I think it would save us some time.
> Allow semver updates for actions

- spec/legacy_lib/insert/insert_bank_account_spec.rb
- spec/legacy_lib/insert/insert_card_spec.rb
- spec/legacy_lib/insert/insert_charge_spec.rb
- spec/legacy_lib/insert/insert_payout_spec.rb
- spec/legacy_lib/stripe_account_spec.rb
- spec/spec_helper.rb
- spec/support/contexts/shared_donation_charge_context.rb
- spec/support/stripe_mock_helper.rb
- spec/support/test/stripe_mock_helper_spec.rb
StripeMockHelper wraps StripeMock so you can easily get a common test helper for your test run at any time. Additionally, it delegates any missing methods so you can use it as a drop-in replacement for StripeMock.
> Add StripeMockHelper

- app/views/layouts/embed.html.erb
- app/views/nonprofits/donate.html.erb
There's a bug in Houdini on the donate page where the javascript is added twice. This is not useful and can cause bugs. This corrects this.
> Correct double loading bug

- app/javascript/legacy/nonprofits/supporters/index/timeline.js
We previously removed the functionality for handling emails in the CRM. This cleans up a few bits that we missed.
> Remove unused timeline.show_email code

- types/flyd/index.d.ts
To date, we haven't had any types for `flyd` which prevents us from using it in Typescript. flyd has types in later versions. We could upgrade flyd BUT long term, we don't want to use it. At the same time, there are advantages to having some types for flyd.
This PR backports a subset of the flyd typings from later version of flyd. I wouldn't rely on these too heavily but they're better than nothing.
> Add limited types for flyd which aren't included in version we use

- babel.config.js
[babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports) converts inputs like:
Transforms member style imports:
```typescript
import { Row, Grid as MyGrid } from 'react-bootstrap';
import { merge } from 'lodash';
```
...into default style imports:
```typescript
import Row from 'react-bootstrap/lib/Row';
import MyGrid from 'react-bootstrap/lib/Grid';
import merge from 'lodash/merge';
```
This prevents the full library being loaded which would happen when you import by member.
This should have been only running on production but it was actually only running on development. This addresses that issue.
> Run babel-plugin-transform-imports on production, not development

- babel.config.js
This change will convert:
```typescript
import {merge} from 'lodash;
```
...to:
```typescript
import merge from 'lodash/merge';
```
This prevents all of lodash from being loaded on a build and instead imports just the merge module.
> Add lodash to babel-plugin-transform-imports

- NOTICE-js
- package.json
- yarn.lock
We are using a very old version of superagent. Based on my reading of the [upgrade guide](https://github.com/visionmedia/superagent#upgrading-from-previous-versions), we should be safe. I'm doing some manual testing on CommitChange to verify but the testing should be replicable.
> Update superagent to 7

- NOTICE-js
- package.json
- yarn.lock
node-sass is deprecated and replaced with the sass package instead. Removing it gets rid of a ton of dependencies too so that's nice.
Depends on #1185
> Remove node-sass

- app/assets/stylesheets/components/side_nav.css.scss
Previously, the background of the bounding box for links in the side nav wasn't clickable. This mean you have to be pointing at the icon or text. That's annoying as h*ck.
This changes the layout for side nav links to "block". Now, the entire bounding box if clickable.
> Entire bounding box of a Side Nav link is clickable

- app/javascript/legacy/nonprofits/supporters/index/sidepanel/backport-query-string.spec.ts
- app/javascript/legacy/nonprofits/supporters/index/sidepanel/backport-query-string.ts
- app/javascript/legacy/nonprofits/supporters/index/sidepanel/index.js
querystring isn't needed anymore as `URLSearchParams` exists. I've created an and added an implementation using USP and created specs for verifying it's actually compatible.
> Deprecate the use of querystring in app/javascript/legacy/nonprofits/supporters/index/sidepanel/index.js

- .erb-lint.yml
- Gemfile
- Gemfile.lock
- NOTICE-ruby
Add erb-lin to help lint ERB or HTML files.
Closes https://github.com/houdiniproject/houdini/issues/510
Co-authored-by: luisgfmarques [luisgustavomarques@outlook.com](luisgustavomarques@outlook.com)
This tool will help lint using the included linters or by writing your own.
* Added the  following to the `Gemfile` and run `bundle install`:
```bash
gem 'erb_lint', require: false
```
* Created a `.erb-lint.yml` file, with the following structure:
```bash
---
exclude:
- '**/.github/**/*'
- '**/.stotybook/**/*'
- '**/node_modules/**/*'
linters:
Rubocop:
enabled: true
rubocop_config:
inherit_from:
- .rubocop.yml
```
* At the first time run `bundle install` for install the dependencies specified in the Gemfile.
* Run `bundle exec erblint --lint-all --enable-all-linters` to run all available …
> Add erb-lint

- app/models/nonprofit.rb
- db/migrate/20220713192154_add_modern_achievements.rb
- db/schema.rb
After CVE-2022-32224, I looked at where we use `.serialize`. We used it in a few places in `Nonprofit`. Serialize is kind of unnecessary; if we use jsonb columns then we get serialization for "free". That makes the most sense I think so this change migrates to using jsonb for those columns.
> Convert nonprofits.achievements and .categories to jsonb

- app/javascript/legacy/common/application_view.js
This is legacy code that we don't want to use long term. To simplify migration, we eliminate things from it that we don't use.
- Remove appl.snake_case
- Remove appl.pathname
- Remove appl.select_drop_down and .clear_drop_down
- Remove appl.remove_commas
- Remove appl.get_month
- Remove appl.get_day
- Remove appl.get_year
- Remove appl.remove_ellipsis
- Remove appl.update_all
> Remove unused functions in application_view

- app/legacy_lib/scheduled_jobs.rb
- docs/payments.md
- lib/tasks/legacy_scheduler.rake
- lib/tasks/scheduler.rake
- script/crontab.sh
Change cron job runner name to a more generic one.
Closes #123 
Co-authored-by: Giuulob89 giulialobo89@gmail.com
The name used to be ```heroku_scheduled_job``` due to historical reasons and should be more generic.
* We changed the name from ```heroku_scheduled_job``` to ```cron_job_runner``` and updated all old references of it:
```rb
task :cron_job_runner, [:name] => :environment do |_t, args|
```
* Now to run the task the command is (using pay_recurring_donations job as example):
```sh
$ bin/rails cron_job_runner[pay_recurring_donations]
```
> Change Cron job rake name

- app/javascript/legacy_react/src/lib/vjf_rules.ts
A number of validations aren't actually used. This removes them.
- Remove shouldBeEqualTo validation
- Remove unused isURL validation
- Remove unused isNumber validation
- Remove unused isFilled validation
- Remove some unused property expansions
> Remove unused vjf rules

- NOTICE-js
- app/javascript/components/users/SignInPage.ErrorBoundary.spec.tsx
- app/javascript/legacy_react/src/components/common/__snapshots__/Modal.spec.tsx.snap
- app/javascript/legacy_react/src/components/common/selectable_table_row/connect.tsx
- app/javascript/legacy_react/src/lib/payments/credit_card.spec.ts
- babel.config.js
- jest.config.js
- package.json
- yarn.lock
babel-jest is an officially supported plugin for jest while ts-jest is not. Additionally, since we use babel as part of our build, for consistency, it seems wise to use babel for our jest tests as well.
- Add babel-jest@^26 and remove ts-jest
- Prepare files for babel-jest
> Move to babel-jest from ts-jest

- app/javascript/legacy_react/src/components/common/LabeledFieldComponent.spec.tsx
- app/javascript/legacy_react/src/components/common/Modal.spec.tsx
- app/javascript/legacy_react/src/components/common/ProgressableButton.spec.tsx
- app/javascript/legacy_react/src/components/common/StandardFieldComponent.spec.tsx
- app/javascript/legacy_react/src/components/common/form/ReactInput.spec.tsx
- app/javascript/legacy_react/src/components/common/form/ReactSelect.spec.tsx
- app/javascript/legacy_react/src/components/common/form/ReactTextarea.spec.tsx
- app/javascript/legacy_react/src/components/common/layout.spec.tsx
- app/javascript/legacy_react/src/components/common/selectable_table_row/SelectableTableRow.spec.tsx
- app/javascript/legacy_react/src/lib/api_manager.spec.ts
- app/javascript/legacy_react/src/lib/format.spec.ts
- app/javascript/legacy_react/src/lib/payments/credit_card.spec.ts
- app/javascript/legacy_react/src/lib/regex.spec.ts
A number of jest tests have a jest import. This isn't needed because jest automatically imports itself on run. This removes those imports.
Depends on #1267
> Remove unneed jest imports

- app/controllers/nonprofits_controller.rb
- app/models/nonprofit.rb
- db/migrate/20220822211046_remove_second_and_third_images_from_nonprofit.rb
- db/schema.rb
second_image and third_image were used in a legacy carousel UI. It doesn't exist anymore so let's remove them.
> Remove second_image and third_image from Nonprofit

- tsconfig.json
strict in tsconfig.json implies noImplicitAny:true. Therefore, we can remove the additional noImplicitAny.
> Remove noImplicitAny since its implied by strict

- tsconfig.json
IE is now so deprecated that I think we can drop support for it. Given that, let's move to a newer ES version. We can probably go higher than ES2018 but it's a good step up.
- Targeting ES2018 from Typescript
- Remove scripthost lib from tsconfig.json
> Update Typescript target to es2018

- NOTICE-js
- package.json
- yarn.lock
[rails-erb-loader](https://github.com/usabilityhub/rails-erb-loader) hasn't had a release a few years but is being updated. This PR updates to the current latest git revision.
> Update rails-erb-loader to latest git revision

- app/models/concerns/model/houidable.rb
- spec/models/concerns/model/houidable_spec.rb
Currently, add_houid runs right after initialize on models. That's annoying becuase it's inconsistent with how integer autocreated IDs are added. This changes the behavior so a Houid is generated just before save.
> Switch add_houid to run just before_save

- app/helpers/application_helper.rb
- app/legacy_lib/format/currency.rb
- app/legacy_lib/query_donations.rb
- app/legacy_lib/query_recurring_donations.rb
Uses the nonprofit currency symbol to display the amount of money on donation queries
Closes #1235
Co-authored-by: Giulia Lobo <giulialobo89@gmail.com>
The amount of money was being displayed based on the currency configured on postgres by using postgres type cast to money:
```ruby
Qexpr.new.select([
'donations.created_at',
'(payments.gross_amount/100.00)::money::text AS amount',
'COUNT(recurring_donations.id) > 0 AS recurring',
"STRING_AGG(campaign_gift_options.name, ',') AS campaign_gift_names"
]...
```
Because of this, the `rails spec` command ended up failing in systems with different currency from USD, the right behavior in this cases is to use the nonprofit currency symbol instead of postgres type cast.
Instead of using postgres type cast, we decided to use the `print_currency` …
> Use nonprofit currency symbol on donation queries

- Gemfile.lock
Reverts houdiniproject/houdini#1432
This shouldn't have been merged because it was actually unsuccessful. Boo mistakes from @wwahammy! :smile:
> Revert "Bump turbo_test from 0.1.2 to 0.2.0"

- app/legacy_lib/create_stripe_account.rb
I'm just dusting off a demo production install of Houdini after 8 months or so and ran into the following error after doing a `git pull` and starting up the production instance (`source .env && bin/rails server --log-to-stdout`). Appears to be just a syntax error from a change back in August 2022, which is fixed in this merge request.
I'm curious as to how the syntax error managed to survive this long though. Am I missing something?
```
Jun 20 00:59:57 donationtest systemd[1]: Started Houdini.
Jun 20 00:59:58 donationtest bash[2248081]: => Booting Puma
Jun 20 00:59:58 donationtest bash[2248081]: => Rails 6.1.7.3 application starting in production
Jun 20 00:59:58 donationtest bash[2248081]: => Run `bin/rails server --help` for more startup options
Jun 20 00:59:58 donationtest …
```
> Fix syntax error in create_stripe_account.rb

- app/mailers/payment_mailer.rb
> Pass locale into PaymentNotificationEmailDonorJob in PaymentMailer#resend_donor_receipt

- app/javascript/components/common/SideNav/AdminMenu.tsx
- app/javascript/components/common/SideNav/Link.tsx
- app/javascript/components/common/SideNav/Section.tsx
- app/javascript/components/common/SideNav/UserMenu.tsx
- app/javascript/components/common/SideNav/index.tsx
- Add Sidenav.Section
- Add SideNav.Link
> Componentize Sidenav

- .github/workflows/js.yml
- README.md
- docs/getting_started_wsl2.md
- package.json
- script/test.sh
`yarn jest` often caused conflict with other tools many of them expect `yarn jest` to not run anytbing other than the Jest command. This renames that NPM script to `test:js`
> Switch to test:js

- app/javascript/legacy_react/src/components/common/LabeledFieldComponent.spec.tsx
- app/javascript/legacy_react/src/components/common/Modal.spec.tsx
- app/javascript/legacy_react/src/components/common/ProgressableButton.spec.tsx
- app/javascript/legacy_react/src/components/common/ScreenReaderOnlyText.spec.tsx
- app/javascript/legacy_react/src/components/common/StandardFieldComponent.spec.tsx
- app/javascript/legacy_react/src/components/common/__snapshots__/LabeledFieldComponent.spec.tsx.snap
- app/javascript/legacy_react/src/components/common/__snapshots__/Modal.spec.tsx.snap
- app/javascript/legacy_react/src/components/common/__snapshots__/ProgressableButton.spec.tsx.snap
- app/javascript/legacy_react/src/components/common/__snapshots__/ScreenReaderOnlyText.spec.tsx.snap
- app/javascript/legacy_react/src/components/common/__snapshots__/StandardFieldComponent.spec.tsx.snap
- **Update ProgressableButton test**
- **Update one more test**
- **Switch ProgressiveButton tests away from enzyme**
- **Start to update Modal.spec**
> update to react test library

- .github/workflows/code-scanning.yml
- .github/workflows/single-matrix-pr.yml
- Gemfile
- Gemfile.lock
- gems/bess/bess.gemspec
- **Use standard rubocop config**
- **Update the code-scanning**
- **Switch to using ubuntu-latest**
- **Try again**
- **Lock concurrent-ruby to 1.3.4**
> Lock concurrent-ruby
